import { HARD_SAFETY } from './contracts.js';
const clone=v=>structuredClone(v??null); const clean=(v,n=200)=>String(v??'').trim().slice(0,n);
export function evaluatePolicy({operation='execution',project_id,context={},policies={}}={}){const errors=[]; if(context.production===true)errors.push('PRODUCTION_LOCKED');if(context.real_customer_data===true)errors.push('REAL_CUSTOMER_DATA_LOCKED');if(context.real_money_movement===true)errors.push('REAL_MONEY_MOVEMENT_LOCKED');if(context.mass_email===true)errors.push('MASS_EMAIL_LOCKED');if(context.automatic_paid_overflow===true||Number(context.variable_cost_eur||0)>0)errors.push('COST_GATE_BLOCKED');if(context.external_write===true&&context.approved!==true)errors.push('UNAPPROVED_EXTERNAL_WRITE_BLOCKED');if(context.source_project_id&&context.source_project_id!==project_id)errors.push('CROSS_PROJECT_ACCESS_BLOCKED');return {ok:!errors.length,operation,project_id:clean(project_id,160),errors,evaluated:['project_policy','provider_policy','cost_policy','data_policy','production_policy','approval_policy'],effective_policies:clone(policies),hard_safety:clone(HARD_SAFETY)};}
export function credentialRoute({credential_ref,project_id,credential_registry={},provider,environment='staging'}={}){if(!credential_ref)return {ok:false,error:'CREDENTIAL_REF_REQUIRED'};const c=credential_registry[credential_ref];if(!c)return {ok:false,error:'CREDENTIAL_REF_UNAVAILABLE'};const errors=[];if(c.project_id!==project_id)errors.push('CREDENTIAL_PROJECT_OWNERSHIP_MISMATCH');if(c.provider!==provider)errors.push('CREDENTIAL_PROVIDER_MISMATCH');if(c.environment!==environment)errors.push('CREDENTIAL_ENVIRONMENT_MISMATCH');if(!Array.isArray(c.permission_scope)||!c.permission_scope.length)errors.push('CREDENTIAL_SCOPE_REQUIRED');return {ok:!errors.length,errors,credential:{credential_ref,project_id,provider,environment,permission_scope:clone(c.permission_scope),secret_value_exposed:false}};}
export function approvalNode({approval_id,project_id,reason,expires_at,state='waiting'}={}){const states=['waiting','approved','rejected','expired'];return {ok:states.includes(state),approval:{schema:'riosystems.approval-node.v2',approval_id:clean(approval_id,160),project_id:clean(project_id,160),reason:clean(reason,500),state:states.includes(state)?state:'waiting',expires_at:clean(expires_at,80)||null,production:false}};}
export class VersionRegistry{#items=new Map(); publish({automation_id,version,revision=1,graph,provider_build={},change_reason='',validation_status='SYNTHETIC_ONLY'}={}){const key=`${automation_id}@${version}.${revision}`;if(this.#items.has(key))return {ok:false,error:'IMMUTABLE_VERSION_EXISTS'};const record={automation_id,version,revision,created_at:new Date(0).toISOString(),change_reason,graph_hash:graph?.graph_hash||null,provider_build:clone(provider_build),validation_status,graph:clone(graph),immutable:true,production:false};this.#items.set(key,record);return {ok:true,record:clone(record)}} list(automation_id){return [...this.#items.values()].filter(x=>x.automation_id===automation_id).map(clone)} get(key){return clone(this.#items.get(key)||null)}}
export function rollbackPlan({automation_id,current_version,history=[],reason}={}){const idx=history.findIndex(x=>String(x.version)===String(current_version));const previous=idx>0?history[idx-1]:null;if(!previous||previous.validation_status!=='KNOWN_GOOD')return {ok:false,error:'PREVIOUS_KNOWN_GOOD_VERSION_REQUIRED'};return {ok:true,rollback:{automation_id,current_version,previous_known_good_version:previous.version,rollback_reason:clean(reason,500),rollback_validation:['graph_hash_match','synthetic_test','policy_check'],rollback_plan:{activate_version:previous.version,external_execution:false},production:false}};}
export function canaryReleaseContract({automation_id,current_version,next_version,percentage=5}={}){const p=Math.min(Math.max(Number(percentage),1),25);return {schema:'riosystems.canary-release.v2',automation_id,current_version,next_version,traffic:{current:100-p,next:p},guardrails:['synthetic_test_required','shadow_compare_required','rollback_required','operator_approval_required'],activation_allowed:false,production:false};}
export function isolationCheck({request_project_id,resource_project_id}={}){return {ok:Boolean(request_project_id)&&request_project_id===resource_project_id,error:request_project_id===resource_project_id?null:'CROSS_PROJECT_ACCESS_BLOCKED'};}
