import { CANONICAL_NODE_TYPES, CANONICAL_EDGE_TYPES, HARD_SAFETY } from './contracts.js';
const clone=v=>structuredClone(v??null); const clean=(v,n=200)=>String(v??'').trim().slice(0,n);
function hash(text){let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')}
export function canonicalGraph({automation_id,project_id,nodes=[],edges=[],metadata={}}={}){
 const errors=[]; const ids=new Set(); if(!clean(project_id)) errors.push('PROJECT_ID_REQUIRED'); if(!nodes.length) errors.push('NODES_REQUIRED');
 for(const n of nodes){if(!CANONICAL_NODE_TYPES.includes(n.type)) errors.push(`NODE_TYPE_INVALID:${n.type}`); if(!clean(n.id)) errors.push('NODE_ID_REQUIRED'); if(ids.has(n.id)) errors.push(`DUPLICATE_NODE:${n.id}`); ids.add(n.id); if(n.project_id&&n.project_id!==project_id) errors.push(`CROSS_PROJECT_NODE_BLOCKED:${n.id}`);}
 for(const e of edges){if(!CANONICAL_EDGE_TYPES.includes(e.type)) errors.push(`EDGE_TYPE_INVALID:${e.type}`); if(!ids.has(e.from)||!ids.has(e.to)) errors.push(`EDGE_NODE_UNKNOWN:${e.from}:${e.to}`);}
 const adj=new Map([...ids].map(id=>[id,[]])); for(const e of edges) if(adj.has(e.from)&&adj.has(e.to)) adj.get(e.from).push(e.to); const visiting=new Set(),done=new Set(); const dfs=id=>{if(visiting.has(id))return true;if(done.has(id))return false;visiting.add(id);for(const x of adj.get(id)||[])if(dfs(x))return true;visiting.delete(id);done.add(id);return false}; if([...ids].some(dfs)) errors.push('CYCLIC_EXECUTION');
 const core={schema:'riosystems.canonical-automation-graph.v2',automation_id:clean(automation_id||`${project_id}:automation`,220),project_id:clean(project_id,160),nodes:clone(nodes).map(n=>({...n,project_id,credential_ref:n.credential_ref||null,production:false})),edges:clone(edges),metadata:clone(metadata),failure_policy:clone(metadata.failure_policy||{mode:'fail_closed'}),provider_neutral:true,hard_safety:clone(HARD_SAFETY)};
 return {ok:!errors.length,errors,graph:errors.length?null:{...core,graph_hash:hash(JSON.stringify(core))}};
}
export function dependencyGraph(automations=[]){ const deps=[]; for(const a of automations){for(const ev of a.consumes||[]){for(const b of automations){if(a.automation_id!==b.automation_id&&(b.produces||[]).includes(ev)) deps.push({from:b.automation_id,to:a.automation_id,event_type:ev});}}} return {schema:'riosystems.automation-dependency-graph.v2',automations:automations.map(a=>({automation_id:a.automation_id,project_id:a.project_id})),dependencies:deps}; }
export function analyzeBlastRadius({change={},automations=[]}={}){ const affected=automations.filter(a=>(a.consumes||[]).includes(change.event_type)||(a.produces||[]).includes(change.event_type)||(a.schema_refs||[]).includes(change.schema_ref)); return {schema:'riosystems.blast-radius.v2',known:automations.length>0,affected_automations:affected.map(a=>a.automation_id),affected_projects:[...new Set(affected.map(a=>a.project_id))],affected_events:[...new Set([change.event_type,...affected.flatMap(a=>a.consumes||[]),...affected.flatMap(a=>a.produces||[])].filter(Boolean))],affected_providers:[...new Set(affected.flatMap(a=>a.providers||[]))],affected_data:[...new Set(affected.flatMap(a=>a.data_refs||[]))],possible_customer_impact:affected.some(a=>a.customer_facing===true)?'POSSIBLE':'NONE_IN_SYNTHETIC_REGISTRY',rollback_scope:affected.map(a=>({automation_id:a.automation_id,rollback_to:a.previous_known_good_version||null})),safe_to_change:automations.length>0&&!affected.some(a=>a.previous_known_good_version===undefined),manual_review_required:automations.length===0}; }
export function lintAutomation(graph){ const issues=[]; if(!graph?.nodes) return {ok:false,issues:['GRAPH_REQUIRED']}; const ids=new Set(graph.nodes.map(n=>n.id)); const incoming=new Map([...ids].map(x=>[x,0])); const adj=new Map([...ids].map(x=>[x,[]])); for(const e of graph.edges||[]){incoming.set(e.to,(incoming.get(e.to)||0)+1);adj.get(e.from)?.push(e.to);} const side=new Set(['database','notification','webhook','action','ai_task','subflow']); for(const n of graph.nodes){if(side.has(n.type)&&!n.idempotency_key&&!n.idempotency_required) issues.push(`MISSING_IDEMPOTENCY:${n.id}`); if(side.has(n.type)&&!n.retry_policy) issues.push(`MISSING_RETRY:${n.id}`); if(side.has(n.type)&&!n.validation) issues.push(`MISSING_VALIDATION:${n.id}`); if(n.credential!==undefined) issues.push(`SECRET_EXPOSURE:${n.id}`); if(n.timeout_ms===undefined) issues.push(`MISSING_TIMEOUT:${n.id}`); if(n.production===true) issues.push(`UNSAFE_WRITE:${n.id}`); if(n.requires_approval===true&&!n.approval_class) issues.push(`MISSING_APPROVAL:${n.id}`); if(n.type!=='trigger'&&incoming.get(n.id)===0) issues.push(`UNREACHABLE_NODE:${n.id}`);} if(!graph.failure_policy) issues.push('MISSING_ERROR_HANDLING'); if(!(graph.nodes||[]).every(n=>n.observability===true)) issues.push('MISSING_OBSERVABILITY'); const visiting=new Set(),done=new Set(); const dfs=id=>{if(visiting.has(id))return true;if(done.has(id))return false;visiting.add(id);for(const x of adj.get(id)||[])if(dfs(x))return true;visiting.delete(id);done.add(id);return false}; if([...ids].some(dfs))issues.push('CYCLIC_EXECUTION'); return {ok:issues.length===0,issues}; }
export function optimizeAutomation(graph){ const ops=[]; const nodes=graph?.nodes||[]; const sig=new Map(); for(const n of nodes){const s=`${n.type}:${JSON.stringify(n.config||{})}`; if(sig.has(s)) ops.push({type:'duplicate_step',nodes:[sig.get(s),n.id],estimated_effect:'one fewer equivalent step',risk:'LOW',recommended_change:'deduplicate'}); else sig.set(s,n.id); if(n.type==='ai_task'&&n.config?.deterministic===true) ops.push({type:'unnecessary_ai_call',nodes:[n.id],estimated_effect:'lower cost and latency',risk:'MEDIUM',recommended_change:'replace with deterministic transform'}); if(n.type==='action'&&n.config?.poll_interval_ms&&n.config.poll_interval_ms<60000) ops.push({type:'excessive_polling',nodes:[n.id],estimated_effect:'fewer provider calls',risk:'LOW',recommended_change:'increase interval or event-drive'}); if(n.config?.provider_cost_class==='EXPENSIVE') ops.push({type:'expensive_provider_usage',nodes:[n.id],estimated_effect:'potential lower runtime cost',risk:'MEDIUM',recommended_change:'evaluate compatible lower-cost route'}); if(n.type==='transform'){const next=(graph.edges||[]).find(e=>e.from===n.id&&e.type==='success');const target=nodes.find(x=>x.id===next?.to);if(target?.type==='transform')ops.push({type:'unnecessary_transform_chain',nodes:[n.id,target.id],estimated_effect:'fewer processing steps',risk:'LOW',recommended_change:'merge transforms'});} if(n.config?.parallelizable===true){const serial=(graph.edges||[]).find(e=>e.from===n.id&&e.type==='success');if(serial)ops.push({type:'serial_parallel_candidate',nodes:[n.id,serial.to],estimated_effect:'potential lower latency',risk:'MEDIUM',recommended_change:'validate and parallelize independent operations'});} if((n.retry_policy?.max_attempts||0)>5) ops.push({type:'unbounded_retry',nodes:[n.id],estimated_effect:'prevent request storm',risk:'HIGH',recommended_change:'cap retry'});} return {optimization_opportunities:ops}; }
export function qualityGate({graph,synthetic_test_passed=false,provider_supported=false,policy_compliant=false}={}){const lint=lintAutomation(graph); const checks={graph_valid:Boolean(graph?.graph_hash),retry_safe:!(lint.issues||[]).some(x=>x.includes('RETRY')),idempotent:!(lint.issues||[]).some(x=>x.includes('IDEMPOTENCY')),observable:!(lint.issues||[]).includes('MISSING_OBSERVABILITY'),policy_compliant:Boolean(policy_compliant),schema_valid:Boolean(graph?.schema),provider_supported:Boolean(provider_supported),synthetic_test_passed:Boolean(synthetic_test_passed)}; return {passed:Object.values(checks).every(Boolean),checks};}
