import { retryPolicyContract, FAILURE_CLASSES } from './contracts.js';
const clone=v=>structuredClone(v??null);
export function classifyFailure(error={}){const c=String(error.code||error.type||'').toLowerCase();const map=[['429','rate_limit'],['rate_limit','rate_limit'],['auth','authentication_failure'],['schema','schema_change'],['mapping','mapping_failure'],['missing','missing_data'],['invalid','invalid_payload'],['timeout','timeout'],['etimedout','timeout'],['dependency','dependency_failure'],['logic','logic_failure'],['down','external_service_down'],['503','temporary_provider_error'],['502','temporary_provider_error'],['500','temporary_provider_error']];return map.find(([k])=>c.includes(k))?.[1]||'logic_failure';}
export function autoRepairPlan(error={}){const cls=classifyFailure(error);const allowed={temporary_provider_error:'retry',rate_limit:'backoff',schema_change:'field_alias_only',mapping_failure:'safe_mapping_correction',timeout:'timeout_backoff',external_service_down:'retry_or_fallback'};const action=allowed[cls]||null;return {failure_class:cls,repairable:Boolean(action),repair_action:action,automatic_allowed:Boolean(action)&&!['authentication_failure','logic_failure'].includes(cls),blocked_repairs:['credential_changes','permission_escalation','money_movement','production_routing','unknown_schema_destruction','mass_communication']};}
export function retrySchedule(error={},policyInput={}){const p=retryPolicyContract(policyInput).policy;const cls=classifyFailure(error);const retryable=p.retryable_errors.includes(cls);const attempts=[];if(retryable&&p.strategy!=='no_retry'){for(let i=1;i<p.max_attempts;i++){let d=p.delay_ms;if(p.strategy==='exponential_backoff')d*=2**(i-1);if(p.strategy==='provider_retry_after'&&Number(error.retry_after_ms)>0)d=Number(error.retry_after_ms);attempts.push({attempt:i+1,delay_ms:Math.min(d,30000)});}}return {retryable,policy:p,attempts,infinite_retry:false};}
export class CircuitBreaker{constructor({failure_threshold=3,recovery_success_threshold=1}={}){this.failure_threshold=failure_threshold;this.recovery_success_threshold=recovery_success_threshold;this.state='CLOSED';this.failures=0;this.halfOpenSuccess=0;} recordFailure(){this.failures++;if(this.failures>=this.failure_threshold)this.state='OPEN';return this.snapshot()} allowProbe(){if(this.state==='OPEN'){this.state='HALF_OPEN';return true}return this.state==='CLOSED'} recordSuccess(){if(this.state==='HALF_OPEN'){this.halfOpenSuccess++;if(this.halfOpenSuccess>=this.recovery_success_threshold){this.state='CLOSED';this.failures=0;this.halfOpenSuccess=0}}else{this.failures=0}return this.snapshot()} snapshot(){return {state:this.state,failures:this.failures}}}
export class DeadLetterQueue{#items=[]; push({event,automation_id,failure_reason,retry_count=0,repair_status='pending',replay_allowed=true}={}){const x={event_id:event?.event_id||null,automation_id,failure_reason,payload_reference:event?.payload_reference||`ref:${event?.event_id||'unknown'}`,failed_at:new Date(0).toISOString(),retry_count,repair_status,replay_allowed:Boolean(replay_allowed),payload_duplicated:false};this.#items.push(x);return clone(x)} list(){return this.#items.map(clone)} remove(event_id){this.#items=this.#items.filter(x=>x.event_id!==event_id)}}
export function recoveryInbox(dlq=[]){const allowed=new Set(['failed','waiting_for_retry','needs_approval','repair_available','blocked','recovered']);return dlq.map(x=>{const raw=x.repair_status==='available'?'repair_available':x.repair_status;const state=allowed.has(raw)?raw:(x.replay_allowed?'failed':'blocked');return {event_id:x.event_id,automation_id:x.automation_id,state,failure_reason:x.failure_reason,retry_count:x.retry_count};});}
export function replayPlan({original_event,original_version,target_version,replay_reason,side_effect_policy='simulate_only',idempotency_check=true}={}){const errors=[];if(!original_event?.event_id)errors.push('ORIGINAL_EVENT_REQUIRED');if(!idempotency_check)errors.push('IDEMPOTENCY_CHECK_REQUIRED');if(side_effect_policy!=='simulate_only')errors.push('EXTERNAL_SIDE_EFFECT_REPLAY_BLOCKED');return {ok:!errors.length,errors,replay:{original_event:clone(original_event),original_version,target_version,original_timestamp:original_event?.timestamp||null,replay_reason,side_effect_policy:'simulate_only',idempotency_check:true,external_side_effects:false}};}
export function rateLimitDecision({current_count=0,limit=60,retry_after_ms=1000}={}){return current_count>=limit?{allowed:false,action:'queue_delay',retry_after_ms:Math.max(1,retry_after_ms)}:{allowed:true,action:'execute'};}
export function concurrencyDecision({active=0,max_parallel=1,project_active=0,project_limit=4,provider_active=0,provider_limit=8}={}){const allowed=active<max_parallel&&project_active<project_limit&&provider_active<provider_limit;return {allowed,reason:allowed?null:'CONCURRENCY_LIMIT',limits:{automation:max_parallel,project:project_limit,provider:provider_limit}};}
export function timeoutPolicy({timeout_ms=5000}={}){return {timeout_ms:Math.min(Math.max(Number(timeout_ms),100),30000),hang_forever:false,on_timeout:'classify_then_bounded_recovery'};}
export function sagaContract({steps=[],compensation_steps=[]}={}){return {schema:'riosystems.automation-saga.v2',steps:clone(steps),compensation_steps:clone(compensation_steps),state:'PLANNED',recovery_state:'NOT_STARTED',automatic_destructive_compensation:false,approval_required_for_destructive:true,production:false};}
export function selfHealingDecision(error={}){const repair=autoRepairPlan(error);return {failure_class:repair.failure_class,diagnosis:`classified:${repair.failure_class}`,repairability:repair.repairable?'BOUNDED_SAFE':'MANUAL_REQUIRED',repair_plan:repair,execute_safe_patch:repair.automatic_allowed,retry_after_patch:repair.automatic_allowed,validate_after_retry:true};}
