import { buildIdempotencyKey, InMemoryIdempotencyStore } from '../automation-v1/idempotency.js';
import { redactSecrets } from '../automation-v1/observability.js';
import { evaluatePolicy } from './governance.js';
import { routeProvider } from './providers.js';
import { qualityGate } from './graph.js';
const clone=v=>structuredClone(v??null);
function topological(graph){const indeg=new Map(graph.nodes.map(n=>[n.id,0]));const out=new Map(graph.nodes.map(n=>[n.id,[]]));for(const e of graph.edges||[]){indeg.set(e.to,(indeg.get(e.to)||0)+1);out.get(e.from)?.push(e.to)}const q=[...indeg].filter(([,d])=>d===0).map(([id])=>id);const result=[];while(q.length){const id=q.shift();result.push(graph.nodes.find(n=>n.id===id));for(const x of out.get(id)||[]){indeg.set(x,indeg.get(x)-1);if(indeg.get(x)===0)q.push(x)}}return result;}
function sideEffect(n){return ['database','notification','webhook','action','ai_task','subflow'].includes(n.type);}
export function dryRunAutomation({graph,input={},provider_requirements={}}={}){if(!graph?.nodes)return {ok:false,error:'GRAPH_REQUIRED'};const planned=[];const blocked=[];let calls=0;for(const n of topological(graph)){const route=routeProvider({capabilities:[({database:'database',notification:'notification',ai_task:'ai_task',webhook:'webhook',action:'http',subflow:'subflow'}[n.type])].filter(Boolean),...provider_requirements});if(route.selected&&route.selected!=='riosystems-native-automation'&&sideEffect(n))calls++;const policy=evaluatePolicy({operation:'execution',project_id:graph.project_id,context:{production:false,real_customer_data:false,variable_cost_eur:0,external_write:false}});const item={node_id:n.id,type:n.type,provider:route.selected,simulated:true,side_effect:sideEffect(n),policy_ok:policy.ok};planned.push(item);if(!policy.ok)blocked.push({...item,reasons:policy.errors});}return {ok:blocked.length===0,schema:'riosystems.automation-dry-run.v2',planned_actions:planned,planned_side_effects:planned.filter(x=>x.side_effect).map(x=>({...x,external_performed:false})),blocked_actions:blocked,estimated_provider_calls:calls,validation_result:blocked.length?'BLOCKED':'PASS',production:false,real_external_writes:false,variable_cost_eur:0};}
export async function syntheticExecute({graph,event,input={},idempotency_store,failures={}}={}){const dry=dryRunAutomation({graph,input});if(!dry.ok)return {ok:false,dry_run:dry};const store=idempotency_store||new InMemoryIdempotencyStore();const steps=[];let current=clone(input);for(const n of topological(graph)){const error=failures[n.id];if(error){steps.push({node_id:n.id,status:'FAILED',error:redactSecrets(error),external_side_effect:false});return {ok:false,status:'FAILED',steps,event_preserved:true,current,production:false};}let duplicate=false;let key=null;if(n.idempotency_required||sideEffect(n)){key=n.idempotency_key||buildIdempotencyKey({namespace:'automation-v2',project_id:graph.project_id,workflow_id:graph.automation_id,node_id:n.id,payload:{event_id:event?.event_id,input}});const claim=store.claim(key,{automation_id:graph.automation_id,node_id:n.id});if(!claim.claimed&&claim.duplicate)duplicate=true;else store.complete(key,{output:current});}steps.push({node_id:n.id,type:n.type,status:duplicate?'DUPLICATE_SKIPPED':'COMPLETED',idempotency_key:key,provider:dry.planned_actions.find(x=>x.node_id===n.id)?.provider,external_side_effect:false,simulated:true});if(n.type==='transform'&&current&&typeof current==='object')current={...current,_mapped:true};if(n.type==='ai_task')current={...current,ai_result:'synthetic-qualified'};}const trace={correlation_id:event?.correlation_id||`${graph.project_id}:trace`,event_id:event?.event_id||null,automation_id:graph.automation_id,project_id:graph.project_id,version:graph.version||1,execution_id:`synthetic:${graph.graph_hash}`,provider:[...new Set(steps.map(x=>x.provider).filter(Boolean))],started_at:new Date(0).toISOString(),completed_at:new Date(0).toISOString(),duration:0,status:'COMPLETED',retry_count:0,error_class:null,recovery_status:'NOT_REQUIRED',payload_logged:false};return {ok:true,status:'COMPLETED',steps,output:current,trace,idempotency_entries:store.snapshot(),production:false,real_external_writes:false,variable_cost_eur:0};}
export async function syntheticWorkflowTest(args={}){const run=await syntheticExecute(args);const gate=qualityGate({graph:args.graph,synthetic_test_passed:run.ok,provider_supported:true,policy_compliant:true});return {ok:run.ok&&gate.passed,run,quality_gate:gate,expected_outputs_valid:run.ok,side_effect_simulation:true};}
export async function shadowCompare({active_graph,candidate_graph,event,input={}}={}){const active=await syntheticExecute({graph:active_graph,event,input});const candidate=await syntheticExecute({graph:candidate_graph,event,input});const a=JSON.stringify(active.output),b=JSON.stringify(candidate.output);return {schema:'riosystems.shadow-mode.v2',behavior_diff:{active_steps:active.steps?.length||0,candidate_steps:candidate.steps?.length||0},data_diff:{equal:a===b},timing_diff:{synthetic:true,delta_ms:0},errors:[...(active.ok?[]:['ACTIVE_FAILED']),...(candidate.ok?[]:['CANDIDATE_FAILED'])],compatibility_status:active.ok&&candidate.ok&&a===b?'COMPATIBLE':'DIFF_REVIEW_REQUIRED',external_side_effects:false,production:false};}
