const clone=(v)=>structuredClone(v??null);const text=(v,m=500)=>String(v??'').trim().slice(0,m);const scoped=(rows,p)=>(rows||[]).filter((r)=>r?.project_id===p);
export const KPI_REGISTRY=Object.freeze([
  {kpi_id:'lead_volume',name:'Lead volume',formula:'count(leads)',source_entities:['lead'],unit:'count'},
  {kpi_id:'qualified_leads',name:'Qualified leads',formula:'count(leads where qualified)',source_entities:['lead'],unit:'count'},
  {kpi_id:'conversion_rate',name:'Lead conversion rate',formula:'converted_leads / leads',source_entities:['lead'],unit:'ratio'},
  {kpi_id:'deal_value',name:'Deal value',formula:'sum(deal.value)',source_entities:['deal'],unit:'currency'},
  {kpi_id:'win_rate',name:'Win rate',formula:'won / (won + lost)',source_entities:['deal'],unit:'ratio'},
  {kpi_id:'loss_rate',name:'Loss rate',formula:'lost / (won + lost)',source_entities:['deal'],unit:'ratio'},
  {kpi_id:'pipeline_velocity',name:'Pipeline velocity',formula:'completed_deals / observed_duration',source_entities:['deal'],unit:'deals_per_day'},
  {kpi_id:'time_to_first_contact',name:'Time to first contact',formula:'avg(first_contact - lead_created)',source_entities:['lead','activity'],unit:'milliseconds'},
  {kpi_id:'stage_duration',name:'Stage duration',formula:'avg(stage exit - entry)',source_entities:['deal'],unit:'milliseconds'},
  {kpi_id:'source_performance',name:'Source performance',formula:'qualified_or_won by source',source_entities:['lead','deal','source'],unit:'ratio'}
]);

export function calculateBusinessMetrics(input={}){
  const p=text(input.project_id,80),leads=scoped(input.leads,p),deals=scoped(input.deals,p),activities=scoped(input.activities,p),qualified=leads.filter((l)=>['qualified','converted'].includes(l.lifecycle_state||l.status)),converted=leads.filter((l)=>['converted'].includes(l.lifecycle_state||l.status)),won=deals.filter((d)=>d.status==='won'),lost=deals.filter((d)=>d.status==='lost'),firstContact=[];
  for(const l of leads){const created=new Date(l.created_at).getTime(),a=activities.filter((x)=>(x.entity_refs||[]).some((r)=>r.id===l.id)&&['call','email','meeting'].includes(x.type)).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp))[0];if(a&&Number.isFinite(created)){const t=new Date(a.timestamp).getTime();if(Number.isFinite(t)&&t>=created)firstContact.push(t-created);}}
  const pipelineValue=deals.filter((d)=>['open','on_hold'].includes(d.status)).reduce((s,d)=>s+Number(d.value||0),0),observedDays=Number(input.observed_days||0),completed=won.length+lost.length;
  return {schema:'riosystems.business-analytics.v2',project_id:p,measurements_only:true,metrics:{lead_volume:leads.length,qualified_leads:qualified.length,conversion_rate:leads.length?converted.length/leads.length:null,deal_value:deals.reduce((s,d)=>s+Number(d.value||0),0),pipeline_value:pipelineValue,win_rate:completed?won.length/completed:null,loss_rate:completed?lost.length/completed:null,pipeline_velocity:observedDays>0?completed/observedDays:null,time_to_first_contact:firstContact.length?firstContact.reduce((a,b)=>a+b,0)/firstContact.length:null},missing_data:[],benchmarks_invented:false};
}
export function defineFunnel(input={}){const steps=(input.steps||[]).map((s,i)=>typeof s==='string'?{key:s,order:i}:{key:text(s.key,100),event_type:text(s.event_type||s.key,120),order:Number.isInteger(s.order)?s.order:i});return{schema:'riosystems.business-funnel.v2',funnel_id:text(input.funnel_id||'default',100),project_id:text(input.project_id,80),steps,definition_only:true};}
export function evaluateFunnel(input={}){const p=text(input.project_id,80),f=input.funnel||defineFunnel(input),events=scoped(input.events,p),counts={};for(const step of f.steps){counts[step.key]=events.filter((e)=>e.event_type===step.event_type||e.type===step.event_type||e.event_type===step.key).length;}const transitions=[];for(let i=1;i<f.steps.length;i++){const a=counts[f.steps[i-1].key],b=counts[f.steps[i].key];transitions.push({from:f.steps[i-1].key,to:f.steps[i].key,rate:a?b/a:null});}return{schema:'riosystems.funnel-result.v2',project_id:p,counts,transitions,derived_from_events:true};}
export function attributionContract(input={}){const touches=(input.touches||[]).filter((t)=>t.project_id===input.project_id).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp));return{schema:'riosystems.attribution.v2',project_id:text(input.project_id,80),entity_id:text(input.entity_id,160),first_touch:touches[0]?clone(touches[0]):null,last_touch:touches.length?clone(touches[touches.length-1]):null,multi_touch:input.multi_touch===true?clone(touches):null,data_complete:touches.length>0,attribution_claimed:touches.length>0};}
export function kpiRegistryManifest(){return{schema:'riosystems.kpi-registry.v2',definitions:clone(KPI_REGISTRY),dashboard_independent:true,formulas_versioned:true};}

export function detectBusinessHealthSignals(input={}){const signals=[],current=input.current||{},previous=input.previous||{};const push=(signal,evidence,severity,recommended)=>signals.push({signal,evidence,severity,recommended_investigation:recommended,absolute_truth:false});if(Number.isFinite(current.time_to_first_contact)&&Number.isFinite(previous.time_to_first_contact)&&current.time_to_first_contact>previous.time_to_first_contact*(input.response_worsening_ratio||1.25))push('lead_response_worsening',{current:current.time_to_first_contact,previous:previous.time_to_first_contact},'warning','inspect staffing, assignment and SLA breaches');if(Number.isFinite(current.pipeline_velocity)&&Number.isFinite(previous.pipeline_velocity)&&current.pipeline_velocity<previous.pipeline_velocity*(input.pipeline_slow_ratio||0.8))push('pipeline_slowing',{current:current.pipeline_velocity,previous:previous.pipeline_velocity},'warning','inspect stage durations and stalled deals');if(Number.isFinite(current.conversion_rate)&&Number.isFinite(previous.conversion_rate)&&current.conversion_rate<previous.conversion_rate*(input.conversion_drop_ratio||0.8))push('conversion_dropping',{current:current.conversion_rate,previous:previous.conversion_rate},'warning','inspect source mix, qualification and stage drop-off');if(Number(current.stale_deals||0)>Number(input.stale_deal_threshold||5))push('high_stale_deal_count',{count:current.stale_deals},'warning','review overdue next actions and owners');return{schema:'riosystems.business-health.v2',signals,evidence_only:true};}
export function detectAnomalies(input={}){const series=Array.isArray(input.series)?input.series:[],threshold=Number(input.change_ratio_threshold??0.5),anomalies=[];for(let i=1;i<series.length;i++){const prev=Number(series[i-1].value),cur=Number(series[i].value);if(!Number.isFinite(prev)||!Number.isFinite(cur)||prev===0)continue;const ratio=(cur-prev)/Math.abs(prev);if(Math.abs(ratio)>=threshold)anomalies.push({metric:input.metric,index:i,previous:prev,current:cur,change_ratio:ratio,type:ratio>0?'spike':'drop',rule_based:true});}return{schema:'riosystems.anomaly-detection.v2',method:'deterministic_rule_based',anomalies,fake_anomalies:false};}
function matchesRule(entity,rule){const v=entity[rule.field];switch(rule.operator){case'eq':return v===rule.value;case'neq':return v!==rule.value;case'gt':return Number(v)>Number(rule.value);case'gte':return Number(v)>=Number(rule.value);case'lt':return Number(v)<Number(rule.value);case'lte':return Number(v)<=Number(rule.value);case'in':return Array.isArray(rule.value)&&rule.value.includes(v);case'exists':return v!==undefined&&v!==null;default:return false;}}
export function evaluateSegment(input={}){const p=text(input.project_id,80),entities=scoped(input.entities,p),rules=input.rules||[],members=entities.filter((e)=>rules.every((r)=>matchesRule(e,r)));return{schema:'riosystems.segment-result.v2',segment_id:text(input.segment_id,100),name:text(input.name,160),entity_type:text(input.entity_type,80),project_id:p,dynamic:input.dynamic!==false,count:members.length,member_ids:members.map((m)=>m.id),materialized_copy_required:false};}
export function buildOperatorCrmView(input={}){const p=text(input.project_id,80),leads=scoped(input.leads,p),deals=scoped(input.deals,p),tasks=scoped(input.tasks,p),activities=scoped(input.activities,p),now=new Date(input.now||Date.now()).getTime();return{schema:'riosystems.operator-crm-view.v2',project_id:p,new_leads:leads.filter((l)=>(l.lifecycle_state||l.status)==='new').length,qualified_leads:leads.filter((l)=>(l.lifecycle_state||l.status)==='qualified').length,stale_leads:Number(input.stale_leads_count??0),open_deals:deals.filter((d)=>['open','on_hold'].includes(d.status)).length,won_deals:deals.filter((d)=>d.status==='won').length,pipeline_value:deals.filter((d)=>['open','on_hold'].includes(d.status)).reduce((s,d)=>s+Number(d.value||0),0),tasks_due:tasks.filter((t)=>t.due_at&&new Date(t.due_at).getTime()>=now&&t.status!=='done').length,overdue_tasks:tasks.filter((t)=>t.status==='overdue'||(t.due_at&&new Date(t.due_at).getTime()<now&&!['done','cancelled'].includes(t.status))).length,recent_activity:clone(activities.slice(-20)),system_warnings:clone(input.system_warnings||[])}};
export function buildBusinessAlert(input={}){const allowed=['stale_high_value_lead','pipeline_drop','unassigned_lead','overdue_task','deal_stuck','data_quality_issue'],type=text(input.type,100);if(!allowed.includes(type))return{ok:false,error:'BUSINESS_ALERT_TYPE_INVALID'};return{ok:true,alert:{schema:'riosystems.business-alert.v2',project_id:text(input.project_id,80),type,severity:text(input.severity||'warning',40),entity_ref:clone(input.entity_ref||null),evidence:clone(input.evidence||{}),recommended_action:text(input.recommended_action,240)||'review',notification_owner:'automation_factory',automatic_notification:false}};}
export function buildCustomerValue(input={}){const values={lifetime_value:input.lifetime_value??null,deal_value:input.deal_value??null,purchase_count:input.purchase_count??null,last_purchase:input.last_purchase??null,relationship_age:input.relationship_age??null};return{schema:'riosystems.customer-value.v2',project_id:text(input.project_id,80),customer_id:text(input.customer_id,160),values,missing:Object.entries(values).filter(([,v])=>v==null).map(([k])=>k),invented:false};}
export function detectRetentionSignals(input={}){const e=input.entity||{},signals=[];if(input.inactive_after&&e.last_activity_at&&new Date(input.now||Date.now())-new Date(e.last_activity_at)>Number(input.inactive_after))signals.push('inactive_customer');if(e.contract_expires_at&&new Date(e.contract_expires_at)<new Date(input.now||Date.now()))signals.push('expired_contract');if(e.status==='lost')signals.push('lost_opportunity');return{schema:'riosystems.retention-signals.v2',project_id:e.project_id,entity_id:e.id,signals,automatic_marketing:false};}
export function analyticsManifest(){return{schema:'riosystems.analytics-engine.v2',metrics:KPI_REGISTRY.map((k)=>k.kpi_id),funnels:true,attribution:['first_touch','last_touch','optional_multi_touch'],business_health:true,anomaly_detection:'rule_based',segments:'dynamic_query',operator_view:true,alerts:true,customer_value:'data_if_available'};}
