import { canonicalBusinessModel, relationshipGraph } from './core.js';

const clone = (v) => structuredClone(v ?? null);
const text = (v, max = 1200) => String(v ?? '').replace(/\s+/g, ' ').trim().slice(0, max);
const slug = (v) => text(v, 100).toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'') || 'business-project';
const words = (v) => text(v, 4000).toLowerCase();

const PIPELINES = Object.freeze({
  short_sales: [['new','New',0.1], ['validated','Validated',0.25], ['qualified','Qualified',0.5], ['proposal','Proposal',0.75], ['won','Won',1], ['lost','Lost',0]],
  consultative: [['new','New',0.05], ['discovery','Discovery',0.2], ['qualified','Qualified',0.4], ['solution','Solution',0.6], ['commercial','Commercial',0.8], ['won','Won',1], ['lost','Lost',0]],
  restaurant: [['new','New inquiry',0.1], ['confirmed','Confirmed',0.8], ['completed','Completed',1], ['cancelled','Cancelled',0]],
  real_estate: [['new','New',0.05], ['qualified','Qualified',0.2], ['viewing','Viewing',0.45], ['offer','Offer',0.7], ['contract','Contract',0.9], ['won','Won',1], ['lost','Lost',0]],
  saas: [['new','New',0.05], ['qualified','Qualified',0.25], ['demo','Demo',0.45], ['trial','Trial',0.6], ['commercial','Commercial',0.8], ['won','Won',1], ['lost','Lost',0]]
});

function pipeline(key, stages) {
  return { pipeline_id: key, key, name: key.replace(/_/g,' '), version: 1, stages: stages.map(([id,name,probability], index) => ({ stage_id: id, key: id, name, stage_order: index, probability, entry_rules: [], exit_rules: [], required_fields: [], sla: null, automation_hooks: [], terminal: ['won','lost','cancelled','completed'].includes(id) })) };
}

export const BUSINESS_RECIPES = Object.freeze({
  local_service: Object.freeze({ recipe_version: '2.0.0', aliases: ['bakery','local business','local service','handwerk','dienstleister','zahnarzt','dentist'], entities: ['company','contact','lead','deal','pipeline','pipeline_stage','activity','task','note','source','tag','event'], optional_entities: ['support_case','service_request'], pipeline: pipeline('new_business', PIPELINES.short_sales), lead_types: ['website inquiry','phone','referral'], kpis: ['lead_volume','qualified_leads','conversion_rate','time_to_first_contact','win_rate'], automation_hooks: ['lead.created','task.overdue'], ai_hooks: ['lead_qualification','next_best_action'], trust_signals: ['response_time','clear ownership','follow-up completion'] }),
  consulting: Object.freeze({ recipe_version: '2.0.0', aliases: ['consulting','beratung','berater','consultant'], entities: ['company','contact','lead','deal','pipeline','pipeline_stage','activity','task','note','source','owner','event'], optional_entities: ['document_link'], pipeline: pipeline('new_business', PIPELINES.consultative), lead_types: ['website','referral','partner','event'], kpis: ['qualified_leads','stage_conversion','pipeline_value','weighted_value','pipeline_velocity','win_rate'], automation_hooks: ['lead.created','deal.stage_changed','deal.won'], ai_hooks: ['lead_qualification','company_summary','deal_summary','next_best_action'], trust_signals: ['discovery quality','proposal follow-up','relationship continuity'] }),
  agency: Object.freeze({ recipe_version: '2.0.0', aliases: ['agency','agentur','marketing agency','web agency'], entities: ['company','contact','lead','deal','pipeline','pipeline_stage','activity','task','note','source','owner','event'], optional_entities: ['project_brief'], pipeline: pipeline('new_business', PIPELINES.consultative), lead_types: ['website','referral','social','ads'], kpis: ['lead_volume','source_performance','conversion_rate','pipeline_value','win_rate'], automation_hooks: ['lead.created','deal.stage_changed'], ai_hooks: ['lead_qualification','activity_summary','next_best_action'], trust_signals: ['portfolio fit','response time','brief completeness'] }),
  restaurant: Object.freeze({ recipe_version: '2.0.0', aliases: ['restaurant','gastronomie','cafe','café','bistro'], entities: ['contact','lead','activity','task','note','source','event'], optional_entities: ['booking','inquiry','event_booking','company'], pipeline: pipeline('inquiries', PIPELINES.restaurant), lead_types: ['website','phone','social','event'], kpis: ['inquiry_volume','response_time','completion_rate'], automation_hooks: ['lead.created'], ai_hooks: ['activity_summary'], trust_signals: ['response time','booking clarity'] }),
  real_estate: Object.freeze({ recipe_version: '2.0.0', aliases: ['real estate','immobilien','makler','broker'], entities: ['company','contact','lead','deal','pipeline','pipeline_stage','activity','task','note','source','owner','event'], optional_entities: ['property','viewing'], pipeline: pipeline('property_sales', PIPELINES.real_estate), lead_types: ['portal','website','phone','referral'], kpis: ['lead_volume','viewing_conversion','pipeline_value','time_in_stage','win_rate'], automation_hooks: ['lead.created','deal.stage_changed'], ai_hooks: ['lead_qualification','next_best_action'], trust_signals: ['response time','viewing follow-up','document completeness'] }),
  SaaS: Object.freeze({ recipe_version: '2.0.0', aliases: ['saas','software','subscription','b2b software'], entities: ['company','contact','lead','deal','pipeline','pipeline_stage','activity','task','note','source','owner','event'], optional_entities: ['subscription','support_case'], pipeline: pipeline('sales', PIPELINES.saas), lead_types: ['website','product','partner','event','ads'], kpis: ['lead_volume','qualified_leads','demo_conversion','trial_conversion','pipeline_velocity','win_rate'], automation_hooks: ['lead.created','deal.stage_changed'], ai_hooks: ['lead_qualification','company_summary'], trust_signals: ['product fit','security evidence','trial engagement'] }),
  professional_services: Object.freeze({ recipe_version: '2.0.0', aliases: ['professional services','anwalt','law firm','accounting','steuerberater','architecture'], entities: ['company','contact','lead','deal','pipeline','pipeline_stage','activity','task','note','source','owner','event'], optional_entities: ['case','document_link'], pipeline: pipeline('engagements', PIPELINES.consultative), lead_types: ['website','referral','phone','partner'], kpis: ['qualified_leads','time_to_first_contact','pipeline_value','win_rate'], automation_hooks: ['lead.created','task.overdue'], ai_hooks: ['lead_qualification','company_summary'], trust_signals: ['confidential handling','response time','matter fit'] })
});

function routeRecipe(mission, explicit = '') { const haystack = `${words(mission)} ${words(explicit)}`; let best = { id: 'local_service', score: 0 }; for (const [id, recipe] of Object.entries(BUSINESS_RECIPES)) { const score = recipe.aliases.reduce((n, alias) => n + (haystack.includes(alias.toLowerCase()) ? Math.max(1, alias.split(/\s+/).length) : 0), 0); if (score > best.score) best = { id, score }; } return best; }
function deriveSources(mission) { const m = words(mission); const candidates = [['website',['website','webseite','form']], ['manual',['manual','manuell']], ['referral',['referral','empfehl']], ['social',['social','linkedin','instagram','facebook']], ['ads',['ads','werbung','google ads']], ['email',['email','e-mail']], ['phone',['phone','telefon']], ['event',['event','messe','webinar']], ['partner',['partner']], ['import',['import','migration','csv']], ['API',['api','webhook']]]; const found = candidates.filter(([,terms]) => terms.some((term) => m.includes(term))).map(([id]) => id); return found.length ? found : ['website','manual']; }
function inferRequirements(mission) { const m = words(mission); const automation = [], ai = [], analytics = []; if (/follow.?up|nachfass|automatisch|automation/.test(m)) automation.push('follow_up_orchestration'); if (/qualif|score|ai|ki/.test(m)) ai.push('lead_qualification'); if (/zusammenfass|summary/.test(m)) ai.push('business_summary'); if (/wo.*verlor|pipeline|conversion|umsatz|revenue|kpi|metric/.test(m)) analytics.push('pipeline_health','conversion_funnel','loss_analysis'); if (/source|quelle|campaign|kampagne/.test(m)) analytics.push('source_performance','attribution'); return { automation: [...new Set(automation)], ai: [...new Set(ai)], analytics: [...new Set(analytics)] }; }

export function discoverBusinessModel(input = {}) {
  const mission = text(input.mission || input.requirement, 5000); if (!mission) return { ok: false, error: 'BUSINESS_DISCOVERY_MISSION_REQUIRED' };
  const route = routeRecipe(mission, input.business_type || input.industry), recipe = BUSINESS_RECIPES[route.id], assumptions = [], risks = [];
  if (!input.business_type && !input.industry) assumptions.push(`business_type inferred as ${route.id}`);
  if (!/pipeline|sales|vertrieb|deal|booking|anfrage|inquiry/.test(words(mission))) assumptions.push('recommended pipeline inferred from industry recipe');
  if (/migration|migrier|import/.test(words(mission))) risks.push('source data mapping and duplicate risk require dry-run');
  if (/sensitive|gesund|medical|patient|legal|anwalt/.test(words(mission))) risks.push('field-level data classification and restricted AI/analytics routing required');
  return { ok: true, discovery: { schema: 'riosystems.business-model-discovery.v2', recommended_business_model: route.id, required_entities: [...recipe.entities], optional_entities: [...recipe.optional_entities], recommended_pipeline: clone(recipe.pipeline), business_events: ['lead.created','lead.qualified','deal.created','deal.stage_changed','deal.won','deal.lost','activity.created','task.created','task.completed'], risks, assumptions, confidence: route.score > 0 ? 'high' : 'medium', recipe_version: recipe.recipe_version } };
}

export function compileBusinessIntent(input = {}) {
  const mission = text(input.mission || input.requirement, 5000); if (!mission) return { ok: false, error: 'CRM_COMPILER_REQUIREMENT_REQUIRED' };
  const discovery = discoverBusinessModel({ ...input, mission }); if (!discovery.ok) return discovery;
  const recipe = BUSINESS_RECIPES[discovery.discovery.recommended_business_model], requirements = inferRequirements(mission);
  const businessName = text(input.business_name || input.business || mission.match(/(?:für|for)\s+([A-ZÄÖÜ][\wÄÖÜäöüß& .-]{2,50})/u)?.[1], 160) || 'Synthetic Business';
  const projectId = slug(input.project_id || businessName), pipelineReq = clone(recipe.pipeline);
  return { ok: true, specification: { schema: 'riosystems.crm-specification.v2', project_id: projectId, business_name: businessName, business_type: discovery.discovery.recommended_business_model, CRM_goal: text(input.CRM_goal || mission, 1200), entities: [...recipe.entities], relationships: relationshipGraph().edges.filter((edge) => recipe.entities.includes(edge.from) || edge.from === 'project'), pipeline_requirements: [pipelineReq], lead_sources: deriveSources(mission), sales_process: pipelineReq.stages.map((s) => s.key), activities: ['call','email','meeting','note','form_submission','website_event','automation_event','status_change','task_completed','support_interaction'], custom_fields: Array.isArray(input.custom_fields) ? clone(input.custom_fields) : [], automation_requirements: [...new Set([...recipe.automation_hooks, ...requirements.automation])], AI_requirements: [...new Set([...recipe.ai_hooks, ...requirements.ai])], analytics_requirements: [...new Set([...recipe.kpis, ...requirements.analytics])], permissions: { current_mode: 'single_operator', future_roles: ['operator','client_admin','client_viewer'] }, retention_requirements: clone(input.retention_requirements || []), data_classification: input.data_classification || 'synthetic', assumptions: [...discovery.discovery.assumptions], risks: [...discovery.discovery.risks], provider_logic_embedded: false, production: false, variable_cost_ceiling_eur: 0 } };
}

export function compileRecipe(input = {}) { const mission = text(input.mission, 5000), compiled = compileBusinessIntent(input); if (!compiled.ok) return compiled; const recipe = BUSINESS_RECIPES[compiled.specification.business_type]; return { ok: true, configuration: { schema: 'riosystems.business-recipe-configuration.v2', project_id: compiled.specification.project_id, recipe_id: compiled.specification.business_type, recipe_version: recipe.recipe_version, specification: compiled.specification, canonical_model: canonicalBusinessModel(), pipelines: [clone(recipe.pipeline)], events: ['lead.created','lead.qualified','deal.created','deal.stage_changed','deal.won','deal.lost'], analytics: [...recipe.kpis], automation_hooks: [...recipe.automation_hooks], AI_hooks: [...recipe.ai_hooks], source_mission: mission } }; }
export function discoverBusinessProcesses(input = {}) { const mission = words(input.mission || input.requirement), base = ['lead_intake','qualification','sales']; if (/onboard|start|delivery|projektstart/.test(mission)) base.push('onboarding'); if (/support|service|ticket/.test(mission)) base.push('support'); if (/retention|renew|reactivat|wiederkehr/.test(mission)) base.push('retention'); if (/review|bewertung/.test(mission)) base.push('review_request'); if (/upsell|cross.sell/.test(mission)) base.push('upsell'); return { schema: 'riosystems.business-process-discovery.v2', processes: [...new Set(base)] }; }
export function buildBusinessProcessGraph(input = {}) { const discovered = discoverBusinessProcesses(input), nodes = [], edges = []; const add = (id, type, label) => { if (!nodes.some((n) => n.id === id)) nodes.push({ id, type, label, project_scoped: true }); }; add('lead-in','event','lead.created'); add('validate','business_action','validate_and_normalize'); add('qualify','decision','qualification'); add('lead-state','state_change','lead.lifecycle'); add('ai-qualify','AI_request','optional_lead_qualification'); add('automation','automation_request','follow_up_orchestration'); add('human','human_task','operator_review'); [['lead-in','validate'],['validate','qualify'],['qualify','lead-state'],['qualify','ai-qualify'],['lead-state','automation'],['automation','human']].forEach(([from,to]) => edges.push({ from,to })); for (const process of discovered.processes.filter((p) => !['lead_intake','qualification'].includes(p))) { const id = `process-${process}`; add(id,'business_action',process); edges.push({ from:'lead-state',to:id }); } return { schema: 'riosystems.business-process-graph.v2', nodes, edges, owner: 'business_factory', execution_owner: 'automation_factory' }; }
export function recommendMissingProcesses(input = {}) { const graph = input.graph || buildBusinessProcessGraph(input), labels = new Set(graph.nodes.map((n) => n.label)), gaps = []; if (input.deals_can_be_won === true && !labels.has('onboarding')) gaps.push({ gap:'onboarding_missing', business_impact:'won deals can lack structured handoff', recommended_process:'onboarding', required_capabilities:['business_process','automation_contract'], automatic_activation:false }); if (input.support_required === true && !labels.has('support')) gaps.push({ gap:'support_process_missing', business_impact:'service requests may not receive a tracked state', recommended_process:'support', required_capabilities:['support_relationship','task_engine'], automatic_activation:false }); return { schema:'riosystems.next-best-process.v2', gaps }; }
export function industryIntelligenceManifest() { return { schema:'riosystems.industry-intelligence.v2', recipes:Object.fromEntries(Object.entries(BUSINESS_RECIPES).map(([id,r]) => [id, { common_entities:r.entities, pipeline_pattern:r.pipeline.key, lead_types:r.lead_types, KPIs:r.kpis, automation_opportunities:r.automation_hooks, trust_signals:r.trust_signals }])), hardcoded_provider_schema:false }; }
