const clone=(v)=>structuredClone(v??null);const text=(v,m=500)=>String(v??'').trim().slice(0,m);
export const EVENT_TYPES=Object.freeze(['lead.created','lead.updated','lead.qualified','lead.converted','contact.created','company.created','deal.created','deal.stage_changed','deal.won','deal.lost','activity.created','task.created','task.completed','customer.updated']);

export function createEventContract(input={}){ const eventType=text(input.event_type,100),projectId=text(input.project_id,80),entityId=text(input.entity_id,160),correlationId=text(input.correlation_id,160); if(!EVENT_TYPES.includes(eventType)||!projectId||!entityId) return {ok:false,error:'BUSINESS_EVENT_CONTRACT_INVALID'}; return {ok:true,event:{schema:'riosystems.business-event.v2',event_id:text(input.event_id,160)||`${projectId}:${eventType}:${entityId}`,event_type:eventType,project_id:projectId,entity_id:entityId,timestamp:input.timestamp||new Date(0).toISOString(),correlation_id:correlationId||`${projectId}:corr:${entityId}`,schema_version:text(input.schema_version||'2.0.0',40),payload_reference:clone(input.payload_reference||null),synthetic:input.synthetic===true}}; }
export function createOutboxRecord(input={}){ const event=input.event; if(!event?.event_id||!event.project_id||!input.mutation_reference) return {ok:false,error:'OUTBOX_INPUT_INVALID'}; return {ok:true,outbox:{schema:'riosystems.business-outbox.v2',outbox_id:text(input.outbox_id,180)||`outbox:${event.event_id}`,project_id:event.project_id,event_id:event.event_id,event_type:event.event_type,correlation_id:event.correlation_id,mutation_reference:clone(input.mutation_reference),status:'pending',attempts:0,created_at:input.created_at||event.timestamp,next_retry_at:null,consumed_at:null,automation_contract_ready:true,external_execution:false}}; }
export function consumeSyntheticOutbox(outbox={},consumer={}){ if(outbox.status==='consumed') return {ok:true,outbox:clone(outbox),idempotent_replay:true}; if(!outbox.project_id||consumer.project_id!==outbox.project_id) return {ok:false,error:'OUTBOX_PROJECT_SCOPE_MISMATCH'}; return {ok:true,outbox:{...clone(outbox),status:'consumed',attempts:Number(outbox.attempts||0)+1,consumed_at:consumer.consumed_at||new Date(0).toISOString()},idempotent_replay:false,correlation_id:outbox.correlation_id}; }
export function buildDeadLetterEvent(input={}){ return {schema:'riosystems.business-dead-letter.v2',event_id:text(input.event_id,160),project_id:text(input.project_id,80),failure:text(input.failure,500),retry_status:text(input.retry_status||'manual_review',80),attempts:Number(input.attempts||0),manual_review:true,correlation_id:text(input.correlation_id,160)||null,sensitive_payload_logged:false}; }

export function buildWebhookIngestionPlan(input={}){ const failures=[]; if(input.authenticated!==true) failures.push('WEBHOOK_AUTH_REQUIRED'); if(input.schema_valid!==true) failures.push('WEBHOOK_SCHEMA_INVALID'); if(!input.project_id) failures.push('WEBHOOK_PROJECT_REQUIRED'); if(!input.idempotency_key) failures.push('WEBHOOK_IDEMPOTENCY_REQUIRED'); return {ok:failures.length===0,status:failures.length?'BLOCKED':'COMMAND_READY',failures,plan:{schema:'riosystems.webhook-ingestion.v2',steps:['authenticate','validate_schema','validate_idempotency','normalize','build_business_command'],project_id:text(input.project_id,80),idempotency_key:text(input.idempotency_key,180),command_type:text(input.command_type||'CreateLeadCommand',100),raw_mutation_allowed:false}}; }

export function buildCommand(input={}){ const type=text(input.command_type,120); if(!type||!input.project_id||!input.actor) return {ok:false,error:'BUSINESS_COMMAND_INVALID'}; return {ok:true,command:{schema:'riosystems.business-command.v2',command_id:text(input.command_id,180)||`${input.project_id}:${type}:${input.idempotency_key||'synthetic'}`,command_type:type,project_id:text(input.project_id,80),actor:clone(input.actor),entity_type:text(input.entity_type,80),entity_id:text(input.entity_id,160)||null,payload:clone(input.payload||{}),expected_version:Number.isInteger(input.expected_version)?input.expected_version:null,idempotency_key:text(input.idempotency_key,180),correlation_id:text(input.correlation_id,160)||null,policy:clone(input.policy||{}),mutation:true}}; }
export function buildQuery(input={}){const t=text(input.query_type,120);if(!t||!input.project_id)return{ok:false,error:'BUSINESS_QUERY_INVALID'};return{ok:true,query:{schema:'riosystems.business-query.v2',query_type:t,project_id:text(input.project_id,80),filters:clone(input.filters||{}),entity_type:text(input.entity_type,80),mutation:false,cross_project:false}};}
export function validateBusinessCommand(input={}){ const c=input.command||input,errors=[]; if(!c.project_id)errors.push('COMMAND_PROJECT_INVALID'); if(!c.actor?.id&&!c.actor?.type)errors.push('COMMAND_ACTOR_UNAUTHORIZED'); if(input.schema_valid===false)errors.push('COMMAND_SCHEMA_INVALID'); if(input.business_rules_valid===false)errors.push('COMMAND_RULES_INVALID'); if(input.state_transition_valid===false)errors.push('COMMAND_STATE_TRANSITION_INVALID'); if(input.idempotency_valid===false)errors.push('COMMAND_IDEMPOTENCY_INVALID'); if(input.policy_valid===false)errors.push('COMMAND_POLICY_INVALID'); if(c.payload?.project_id&&c.payload.project_id!==c.project_id)errors.push('COMMAND_PROJECT_SCOPE_MISMATCH'); return {ok:errors.length===0,errors,status:errors.length?'BLOCKED':'VALIDATED'}; }
export function applyOptimisticMutation(record={},patch={},input={}){ const current=Number(record.version??record.revision??1),expected=Number(input.expected_version); if(!Number.isInteger(expected))return{ok:false,error:'EXPECTED_VERSION_REQUIRED',current_version:current}; if(expected!==current)return{ok:false,error:'OPTIMISTIC_CONCURRENCY_CONFLICT',current_version:current,expected_version:expected}; if(patch.project_id&&patch.project_id!==record.project_id)return{ok:false,error:'CONCURRENCY_PROJECT_SCOPE_MISMATCH'}; return {ok:true,record:{...clone(record),...clone(patch),project_id:record.project_id,version:current+1,revision:current+1,updated_at:input.updated_at||new Date(0).toISOString()},previous_version:current,new_version:current+1}; }
export function buildAuditEntry(input={}){ return {schema:'riosystems.business-audit.v2',audit_id:text(input.audit_id,160)||`${input.project_id}:audit:${input.operation_id||'synthetic'}`,project_id:text(input.project_id,80),who:clone(input.who||{type:'system'}),what:text(input.what,160),when:input.when||new Date(0).toISOString(),source:text(input.source||'business_factory',100),old_state_reference:clone(input.old_state_reference||null),new_state_reference:clone(input.new_state_reference||null),reason:text(input.reason,300)||null,raw_state_logged:false,secrets_logged:false,correlation_id:text(input.correlation_id,160)||null}; }
export function buildArchivePlan(input={}){ return {schema:'riosystems.archive-plan.v2',project_id:text(input.project_id,80),entity_ref:clone(input.entity_ref),active:false,archived_at:input.archived_at||new Date(0).toISOString(),deleted_at:null,hard_delete:false,requires_external_write_approval:true}; }
export function createIdempotencyRegistry(){const seen=new Map();return{check(projectId,key,fingerprint=''){const k=`${projectId}:${key}`,existing=seen.get(k);if(existing)return{ok:true,replay:true,result:clone(existing.result),fingerprint_match:existing.fingerprint===fingerprint};return{ok:true,replay:false};},commit(projectId,key,result,fingerprint=''){const k=`${projectId}:${key}`;if(seen.has(k))return{ok:true,replay:true,result:clone(seen.get(k).result)};seen.set(k,{fingerprint,result:clone(result)});return{ok:true,replay:false,result:clone(result)};},size(){return seen.size;}};}
export function buildObservabilityRecord(input={}){ return {schema:'riosystems.business-operation-observability.v2',operation_id:text(input.operation_id,160),project_id:text(input.project_id,80),command_type:text(input.command_type,120),entity_type:text(input.entity_type,80),entity_id:text(input.entity_id,160)||null,source:text(input.source||'business_factory',100),status:text(input.status,60),started_at:input.started_at||null,completed_at:input.completed_at||null,validation_result:text(input.validation_result,80)||null,event_emitted:input.event_emitted===true,correlation_id:text(input.correlation_id,160)||null,sensitive_fields_logged:false}; }
export function buildCorrelationTrace(input={}){ const projectId=text(input.project_id,80),correlationId=text(input.correlation_id,160),records=(input.records||[]).filter((r)=>r.project_id===projectId&&r.correlation_id===correlationId); return {schema:'riosystems.correlation-trace.v2',project_id:projectId,correlation_id:correlationId,flow:['Web','Business','AI','Automation','Analytics'],records:clone(records),cross_project:false}; }
export function eventSystemManifest(){return{schema:'riosystems.event-system.v2',event_types:[...EVENT_TYPES],outbox:true,dead_letter:true,idempotency:true,optimistic_concurrency:true,commands_queries_separated:true,webhook_ingestion:'validate_before_command',audit:'reference_based',soft_delete:true,correlation:true};}
