import { normalizeBusinessData, detectLeadDuplicates, resolveContactIdentity, resolveCompanyIdentity } from './identity.js';
import { createEventContract } from './events.js';
const clone=(v)=>structuredClone(v??null);const text=(v,m=500)=>String(v??'').trim().slice(0,m);
const DIRECT_PII=new Set(['email','phone','full_name','first_name','last_name','name','address','message','notes','raw_payload','ip','ip_address','user_agent']);
function minimize(obj={}){const out={};for(const [k,v] of Object.entries(obj)){if(DIRECT_PII.has(k.toLowerCase()))continue;if(v==null)continue;if(typeof v==='string')out[k]=v.slice(0,200);else if(typeof v==='number'||typeof v==='boolean')out[k]=v;}return out;}

export function buildWebToCrmPlan(input={}){if(input.synthetic!==true)return{ok:false,error:'WEB_TO_CRM_V2_SYNTHETIC_ONLY'};const projectId=text(input.project_id,80),idempotencyKey=text(input.idempotency_key,180);if(!projectId||!idempotencyKey)return{ok:false,error:'WEB_TO_CRM_SCOPE_REQUIRED'};const normalized=normalizeBusinessData(input.fields||{}),candidate={...normalized.canonical,project_id:projectId,source:input.source||'website',external_id:input.external_id||null},duplicate=detectLeadDuplicates(candidate,input.existing_leads||[]),contact=resolveContactIdentity(candidate,input.contacts||[]),company=resolveCompanyIdentity(candidate,input.companies||[]),persistAction=duplicate.duplicate_probability>=0.9?'link_existing_lead':duplicate.manual_review_required?'manual_review':'create_lead',event=createEventContract({event_type:'lead.created',project_id:projectId,entity_id:duplicate.matching_records?.[0]?.id||`planned:${idempotencyKey}`,correlation_id:input.correlation_id||`${projectId}:web:${idempotencyKey}`,payload_reference:{kind:'planned_lead',idempotency_key:idempotencyKey},synthetic:true});return{ok:true,plan:{schema:'riosystems.web-to-crm.v2',project_id:projectId,flow:['validate','normalize','deduplicate','resolve_contact','resolve_company','persist_plan','business_event'],normalized,candidate,duplicate,contact_resolution:contact.resolution,company_resolution:company.resolution,persist_plan:{action:persistAction,mutation_authorized:false,idempotency_key:idempotencyKey},event:event.event,correlation_id:event.event.correlation_id,external_write:false}};}

const AI_TASK_MAP=Object.freeze({lead_qualification:{task_type:'classification',capability:'business.lead_classification'},company_summary:{task_type:'summarization',capability:'business.summary'},deal_summary:{task_type:'summarization',capability:'business.summary'},next_best_action:{task_type:'decision_support',capability:'business.next_action'},support_sentiment:{task_type:'classification',capability:'business.crm_enrichment'},activity_summary:{task_type:'summarization',capability:'business.summary'}});
export function buildAiEnrichmentRequest(input={}){const mapping=AI_TASK_MAP[input.task];if(!mapping)return{ok:false,error:'AI_ENRICHMENT_TASK_UNSUPPORTED'};if(!input.project_id||!input.entity_id)return{ok:false,error:'AI_ENRICHMENT_SCOPE_REQUIRED'};const dataClass=input.data_classification||'synthetic';if(!['synthetic','internal'].includes(dataClass))return{ok:false,error:'AI_ENRICHMENT_DATA_CLASS_BLOCKED'};return{ok:true,request:{contract:'riosystems.ai-task.v1',task_id:text(input.task_id,160)||`${input.project_id}:${input.task}:${input.entity_id}`,project:text(input.project_id,160),task_type:mapping.task_type,capability:mapping.capability,objective:text(input.objective||`Produce ${input.task} advisory output.`,1000),input:clone(input.input||{}),context:clone(input.context||[]),constraints:['No external side effects.','Do not mutate CRM state.','Do not infer sensitive personal attributes.'],quality_rules:['Return only structured evidence-backed output.'],expected_output_schema:clone(input.expected_output_schema||{type:'object',properties:{result:{type:'string'}},required:['result'],additionalProperties:true}),quality_level:input.quality_level||'Luna',latency_class:input.latency_class||'standard',cost_limit:0,data_sensitivity:dataClass,preferred_provider:input.preferred_provider||null,fallback_allowed:input.fallback_allowed===true,max_attempts:Math.min(3,Math.max(1,Number(input.max_attempts||2))),correlation_id:text(input.correlation_id,160)||null,blind_mutation:false}};}
export function validateAiEnrichmentResult(input={}){const request=input.request,result=input.result;if(!request?.task_id||!result||typeof result!=='object')return{ok:false,error:'AI_RESULT_INVALID'};if(result.project&&result.project!==request.project)return{ok:false,error:'AI_RESULT_PROJECT_SCOPE_MISMATCH'};const status=result.quality?.status||result.quality_status||'unverified';return{ok:true,validated:{schema:'riosystems.ai-enrichment-result.v2',project_id:request.project,entity_id:input.entity_id,task_id:request.task_id,structured_result:clone(result.output||result.result||result),provenance:{source:'ai',task_id:request.task_id,model_route_reference:result.model_route_reference||result.provider||null,generated_at:result.generated_at||new Date(0).toISOString(),confidence:result.confidence??null,quality_status:status,human_verified:input.human_verified===true},persist_plan:{allowed:input.persist_requested===true&&status!=='failed',mutation_authorized:false,requires_business_validation:true},human_confirmed:input.human_verified===true}};}
export function buildAutomationEventContract(input={}){const event=input.event;if(!event?.project_id||!event.event_type)return{ok:false,error:'AUTOMATION_EVENT_INPUT_INVALID'};return{ok:true,contract:{schema:'riosystems.business-automation-contract.v2',project_id:event.project_id,trigger:{type:'crm_event',event_type:event.event_type,event_id:event.event_id},goal:text(input.goal||`React to ${event.event_type}`,600),systems:['business_factory','automation_factory'],data_classification:'synthetic_test_data',execution_frequency:'event_driven',side_effect_level:'safe_synthetic_write',budget:{variable_cost_ceiling_eur:0},approval_requirements:[],idempotency_key:text(input.idempotency_key||`automation:${event.event_id}`,180),correlation_id:event.correlation_id,business_rules_owner:'business_factory',execution_owner:'automation_factory',production:false,external_execution_authorized:false}};}
export function mapEventToPostHogV2(event={}){if(!event.project_id||!event.event_type)return{ok:false,error:'POSTHOG_V2_EVENT_INVALID'};const properties=minimize({schema_version:event.schema_version,project_id:event.project_id,entity_type:event.payload_reference?.entity_type,event_type:event.event_type,synthetic:event.synthetic,correlation_id:event.correlation_id,...(event.analytics_properties||{})});return{ok:true,mapping:{schema:'riosystems.crm-posthog-contract.v2',provider:'posthog',event:event.event_type.replace(/\./g,'_'),distinct_id:`project:${event.project_id}`,properties,person_profiles:'never',contains_direct_pii:false,external_write_authorized:false}};}
export function buildSupportRelationshipContract(input={}){return{schema:'riosystems.support-relationship.v2',project_id:text(input.project_id,80),enabled:input.enabled===true,entities:input.enabled===true?['support_case','service_request','resolution']:[],priorities:['low','normal','high','urgent'],optional:true};}
export function buildCustomerLifecycle(input={}){const states=input.enabled===false?[]:['prospect','lead','qualified','customer','repeat_customer','inactive','churned'];return{schema:'riosystems.customer-lifecycle.v2',project_id:text(input.project_id,80),enabled:input.enabled!==false,states,recipe_configured:true,enforced_for_all_projects:false};}
export function integrationsManifest(){return{schema:'riosystems.business-integrations.v2',web_to_crm:['validate','normalize','deduplicate','resolve','persist_plan','event'],AI_tasks:Object.keys(AI_TASK_MAP),AI_persistence_owner:'business_factory',automation_business_rules_owner:'business_factory',automation_execution_owner:'automation_factory',posthog:'PII-minimized-contract-only',support_optional:true,customer_lifecycle_optional:true,external_writes:false};}
