const clone = (v) => structuredClone(v ?? null);
const text = (v,max=500)=>String(v??'').trim().slice(0,max);

export const STATE_MACHINES = Object.freeze({
  lead: Object.freeze({ new:['validated','archived'], validated:['qualified','unqualified','contacted','archived'], qualified:['contacted','engaged','converted','lost','archived'], unqualified:['validated','archived'], contacted:['engaged','lost','archived'], engaged:['converted','lost','archived'], converted:['archived'], lost:['engaged','archived'], archived:[] }),
  deal: Object.freeze({ open:['on_hold','won','lost','cancelled'], on_hold:['open','won','lost','cancelled'], won:[], lost:[], cancelled:[] }),
  task: Object.freeze({ open:['in_progress','done','cancelled','overdue'], in_progress:['done','cancelled','overdue'], overdue:['in_progress','done','cancelled'], done:[], cancelled:[] })
});

export function validateStateTransition(entityType, from, to) { const machine = STATE_MACHINES[entityType]; if (!machine) return {ok:false,error:'STATE_MACHINE_UNKNOWN'}; if (!Object.hasOwn(machine,from) || !Object.hasOwn(machine,to)) return {ok:false,error:'STATE_UNKNOWN'}; return machine[from].includes(to) ? {ok:true,entity_type:entityType,from,to} : {ok:false,error:'STATE_TRANSITION_NOT_ALLOWED',entity_type:entityType,from,to}; }

export function validatePipeline(input={}) {
  const projectId=text(input.project_id,80), key=text(input.key||input.pipeline_id,100), stages=Array.isArray(input.stages)?input.stages:[], errors=[];
  if(!projectId) errors.push('PIPELINE_PROJECT_REQUIRED'); if(!key) errors.push('PIPELINE_KEY_REQUIRED'); if(stages.length<2) errors.push('PIPELINE_STAGES_REQUIRED');
  const keys=stages.map((s)=>text(s.key||s.stage_id,100)); if(new Set(keys).size!==keys.length) errors.push('PIPELINE_STAGE_KEYS_DUPLICATE');
  const orders=stages.map((s,i)=>Number.isInteger(s.stage_order)?s.stage_order:i); if(new Set(orders).size!==orders.length) errors.push('PIPELINE_STAGE_ORDER_DUPLICATE');
  for(const stage of stages){ const p=Number(stage.probability??0); if(!Number.isFinite(p)||p<0||p>1) errors.push(`PIPELINE_PROBABILITY_INVALID:${stage.key||stage.stage_id}`); if(stage.project_id && stage.project_id!==projectId) errors.push('PIPELINE_PROJECT_SCOPE_MISMATCH'); }
  return {ok:errors.length===0,errors,pipeline:errors.length?null:{schema:'riosystems.pipeline.v2',project_id:projectId,key,version:Number(input.version||1),stages:clone(stages),entry_rules:clone(input.entry_rules||[]),automation_hooks:clone(input.automation_hooks||[])}};
}

export function validateMultiplePipelines(projectId,pipelines=[]){ const errors=[],keys=new Set(); for(const p of pipelines){ const checked=validatePipeline({...p,project_id:p.project_id||projectId}); if(!checked.ok) errors.push(...checked.errors); if(p.project_id&&p.project_id!==projectId) errors.push('CROSS_PROJECT_PIPELINE'); const key=p.key||p.pipeline_id; if(keys.has(key)) errors.push('PIPELINE_KEY_DUPLICATE'); keys.add(key); } return {ok:errors.length===0,errors,count:pipelines.length}; }

export function validateDeal(input={}){ const errors=[]; if(!input.project_id) errors.push('DEAL_PROJECT_REQUIRED'); if(!['open','won','lost','cancelled','on_hold'].includes(input.status)) errors.push('DEAL_STATUS_INVALID'); if(!input.pipeline_id||!input.stage_id) errors.push('DEAL_PIPELINE_STAGE_REQUIRED'); const value=Number(input.value??0),prob=Number(input.probability??0); if(!Number.isFinite(value)||value<0) errors.push('DEAL_VALUE_INVALID'); if(!Number.isFinite(prob)||prob<0||prob>1) errors.push('DEAL_PROBABILITY_INVALID'); return {ok:errors.length===0,errors,deal:errors.length?null:{...clone(input),value,probability:prob,currency:text(input.currency||'EUR',3).toUpperCase()}}; }

export function analyzePipelineHealth(input={}){
  const projectId=text(input.project_id,80), deals=(input.deals||[]).filter((d)=>d.project_id===projectId), activities=(input.activities||[]).filter((a)=>a.project_id===projectId), stages=input.pipeline?.stages||[], stageStats={};
  for(const stage of stages) stageStats[stage.key||stage.stage_id]={entered:0,current:0,wins:0,losses:0,total_time_ms:0,time_samples:0};
  for(const deal of deals){ const stage=deal.stage_key||deal.stage_id; if(stageStats[stage]) stageStats[stage].current+=1; for(const h of deal.stage_history||[]){ const s=stageStats[h.stage_key]; if(!s) continue; s.entered+=1; const start=new Date(h.entered_at).getTime(),end=new Date(h.exited_at||input.now||Date.now()).getTime(); if(Number.isFinite(start)&&Number.isFinite(end)&&end>=start){s.total_time_ms+=end-start;s.time_samples+=1;} } if(deal.status==='won'&&stageStats[stage]) stageStats[stage].wins+=1; if(deal.status==='lost'&&stageStats[stage]) stageStats[stage].losses+=1; }
  const transitions={}; for(const d of deals){ for(const h of d.stage_history||[]){ if(!h.next_stage_key) continue; const k=`${h.stage_key}->${h.next_stage_key}`; transitions[k]=(transitions[k]||0)+1; } }
  const won=deals.filter((d)=>d.status==='won').length,lost=deals.filter((d)=>d.status==='lost').length,open=deals.filter((d)=>['open','on_hold'].includes(d.status)),pipelineValue=open.reduce((s,d)=>s+Number(d.value||0),0),weightedValue=open.reduce((s,d)=>s+Number(d.value||0)*Number(d.probability||0),0);
  return {schema:'riosystems.pipeline-health.v2',project_id:projectId,measurements_only:true,deals_total:deals.length,open_deals:open.length,win_rate:won+lost?won/(won+lost):null,loss_rate:won+lost?lost/(won+lost):null,pipeline_value:pipelineValue,weighted_value:weightedValue,stage_stats:Object.fromEntries(Object.entries(stageStats).map(([k,v])=>[k,{...v,average_time_ms:v.time_samples?v.total_time_ms/v.time_samples:null}])),transition_counts:transitions,activity_count:activities.length,no_benchmark_claims:true};
}

export function detectStaleEntities(input={}){
  const projectId=text(input.project_id,80),now=new Date(input.now||Date.now()).getTime(),leadLimit=Number(input.lead_stale_ms??2*24*3600e3),dealLimit=Number(input.deal_stale_ms??3*24*3600e3),attention=[];
  const check=(entity,type,limit)=>{ if(entity.project_id!==projectId) return; const last=new Date(entity.last_activity_at||entity.updated_at||entity.created_at||0).getTime(),age=Number.isFinite(last)?now-last:Infinity,reasons=[]; if(age>limit)reasons.push('no_activity'); if(!entity.owner_id&&!entity.owner_ref)reasons.push('missing_owner'); if(!entity.next_action&&type==='lead')reasons.push('missing_next_action'); if(entity.due_at&&new Date(entity.due_at).getTime()<now)reasons.push('overdue_follow_up'); if(reasons.length)attention.push({entity_type:type,entity_id:entity.id,attention_required:true,reasons,age_ms:age,recommended_action:reasons.includes('missing_owner')?'review_assignment':reasons.includes('missing_next_action')?'define_next_action':'follow_up_review',automatic_customer_communication:false}); };
  for(const l of input.leads||[]) check(l,'lead',leadLimit); for(const d of input.deals||[]) check(d,'deal',dealLimit); return {schema:'riosystems.stale-detection.v2',project_id:projectId,attention};
}

export function buildNextBestAction(input={}){ const allowed=['call','email','follow_up','qualify','schedule','review','close','archive']; let action='review'; const e=input.entity||{}; if(e.status==='new'||e.lifecycle_state==='new') action='qualify'; else if(!e.next_action) action='follow_up'; else if(e.status==='won'||e.lifecycle_state==='converted') action='close'; else if(e.status==='lost'||e.lifecycle_state==='lost') action='archive'; if(input.preferred_action&&allowed.includes(input.preferred_action)) action=input.preferred_action; return {schema:'riosystems.next-best-action.v2',project_id:e.project_id,entity_ref:{type:input.entity_type||'lead',id:e.id},action,rationale:input.rationale||'deterministic business-rule recommendation',prerequisites:clone(input.prerequisites||[]),AI_advisory_only:input.ai_result!=null,automatic_execution:false}; }

export function buildActivity(input={}){ const allowed=['call','email','meeting','note','form_submission','website_event','automation_event','status_change','task_completed','support_interaction'],type=text(input.type,80); if(!input.project_id||!input.activity_id||!allowed.includes(type)) return {ok:false,error:'ACTIVITY_CONTRACT_INVALID'}; return {ok:true,activity:{schema:'riosystems.activity.v2',activity_id:text(input.activity_id,160),project_id:text(input.project_id,80),entity_refs:clone(input.entity_refs||[]),type,timestamp:input.timestamp||new Date(0).toISOString(),actor:clone(input.actor||{type:'system'}),source:text(input.source||'business_factory',100),correlation_id:text(input.correlation_id,160)||null,metadata:clone(input.metadata||{})}}; }
export function buildTimeline(input={}){ const projectId=text(input.project_id,80),entityId=text(input.entity_id,160),activities=(input.activities||[]).filter((a)=>a.project_id===projectId&&(a.entity_refs||[]).some((r)=>r.id===entityId)); activities.sort((a,b)=>new Date(a.timestamp).getTime()-new Date(b.timestamp).getTime()); return {schema:'riosystems.business-timeline.v2',project_id:projectId,entity_ref:{type:input.entity_type,id:entityId},items:clone(activities),correlation_ids:[...new Set(activities.map((a)=>a.correlation_id).filter(Boolean))]}; }
export function buildTask(input={}){ const status=['open','in_progress','done','cancelled','overdue'].includes(input.status)?input.status:'open',priority=['low','normal','high','urgent'].includes(input.priority)?input.priority:'normal'; return {schema:'riosystems.task.v2',task_id:text(input.task_id,160),project_id:text(input.project_id,80),entity_ref:clone(input.entity_ref),owner:text(input.owner||input.owner_id,160)||null,due_at:input.due_at||null,priority,status,task_type:text(input.task_type||'follow_up',80),created_source:text(input.created_source||'business_factory',100)}; }
export function buildSlaContract(input={}){ return {schema:'riosystems.sla.v2',project_id:text(input.project_id,80),event:text(input.event,100),deadline:clone(input.deadline||{duration_minutes:Number(input.duration_minutes||0)}),priority:text(input.priority||'normal',40),escalation_rule:clone(input.escalation_rule||null),notification_execution_owner:'automation_factory',automatic_notification:false}; }

function compare(value,op,target){ if(op==='eq')return value===target;if(op==='neq')return value!==target;if(op==='gt')return Number(value)>Number(target);if(op==='gte')return Number(value)>=Number(target);if(op==='lt')return Number(value)<Number(target);if(op==='lte')return Number(value)<=Number(target);if(op==='in')return Array.isArray(target)&&target.includes(value);if(op==='exists')return value!==undefined&&value!==null;return false; }
export function evaluateBusinessRule(rule={},context={}){ if(!rule.project_id||!rule.rule_id||!Number.isInteger(rule.version)) return {ok:false,error:'BUSINESS_RULE_CONTRACT_INVALID'}; const conditions=rule.conditions||[],matched=conditions.every((c)=>compare(context[c.field],c.operator,c.value)); return {ok:true,result:{schema:'riosystems.business-rule-result.v2',rule_id:rule.rule_id,version:rule.version,project_id:rule.project_id,matched,actions:matched?clone(rule.actions||[]):[],status:rule.status||'active',activated_at:rule.activated_at||null,testable:true}}; }
export function buildAssignmentDecision(input={}){ const method=['round_robin','manual','region','lead_source','deal_value','specialization'].includes(input.method)?input.method:'manual',candidates=(input.candidates||[]).filter((c)=>c.project_id===input.project_id&&c.active!==false); let owner=null; if(method==='manual') owner=candidates.find((c)=>c.id===input.owner_id)||null; else if(method==='round_robin'&&candidates.length) owner=[...candidates].sort((a,b)=>String(a.id).localeCompare(String(b.id)))[Number(input.sequence||0)%candidates.length]; else owner=candidates.find((c)=>!input.match_field||c[input.match_field]===input.match_value)||null; return {schema:'riosystems.assignment-decision.v2',project_id:input.project_id,method,owner_id:owner?.id||null,automatic_persist:false}; }
export function buildLeadScore(input={}){ const factors=(input.factors||[]).map((f)=>({source:f.source||'business_rule',name:text(f.name,100),value:Number(f.value||0),weight:Number(f.weight??1),contribution:Number(f.value||0)*Number(f.weight??1)})),score=factors.reduce((s,f)=>s+f.contribution,0); return {schema:'riosystems.lead-score.v2',project_id:input.project_id,lead_id:input.lead_id,score:Number(score.toFixed(3)),score_version:text(input.score_version||'v1',40),factors,calculated_at:input.calculated_at||new Date(0).toISOString(),AI_component_advisory:factors.some((f)=>f.source==='ai')}; }
export function lifecycleManifest(){return {schema:'riosystems.lifecycle-engine.v2',state_machines:Object.keys(STATE_MACHINES),lead_states:Object.keys(STATE_MACHINES.lead),deal_states:Object.keys(STATE_MACHINES.deal),task_states:Object.keys(STATE_MACHINES.task),multiple_pipelines:true,SLA:true,business_rules:true,assignment:true,lead_scoring:true};}
