import { resolveSemanticSelector } from "./project-analyzer.js";

function clean(value, max = 4000) { return String(value || "").trim().slice(0, max); }
function includesAny(text, terms) { return terms.some((term) => text.includes(term)); }
function detectIntensity(text) {
  if (includesAny(text, ["viel größer", "deutlich größer", "massiv", "riesig", "extrem", "richtig viel"])) return "strong";
  if (includesAny(text, ["größer", "mehr", "stärker", "dichter", "dunkler", "heller", "realistischer"])) return "medium";
  if (includesAny(text, ["etwas", "leicht", "bisschen", "bishen", "dezent"])) return "light";
  return "normal";
}
function operation(target, action, value, reason, semantic = null) { return { target, action, value, reason, semantic }; }
function extractText(raw, patterns, max = 180) {
  for (const pattern of patterns) { const match = pattern.exec(raw.trim()); if (match?.[1]) return clean(match[1].replace(/[.!]+$/, ""), max); }
  return "";
}
function extractHeadline(raw = "") { return extractText(raw, [/(?:ändere|aendere|setze|mach)\s+(?:die\s+)?(?:hero[- ]?)?(?:headline|überschrift|ueberschrift)\s+(?:auf|zu|in)\s+["„“']?([^\n"„“']{2,180})["„“']?[.!]?$/i, /(?:change|set)\s+(?:the\s+)?(?:hero[- ]?)?(?:headline|heading)\s+(?:to|as)\s+["']?([^\n"']{2,180})["']?[.!]?$/i, /(?:headline|überschrift|ueberschrift)\s*:\s*["„“']?([^\n"„“']{2,180})["„“']?/i]); }
function extractSubheadline(raw = "") { return extractText(raw, [/(?:ändere|aendere|setze|mach)\s+(?:die\s+)?(?:hero[- ]?)?(?:subheadline|unterüberschrift|unterueberschrift|untertitel|beschreibung)\s+(?:auf|zu|in)\s+["„“']?([^\n"„“']{2,260})["„“']?[.!]?$/i, /(?:change|set)\s+(?:the\s+)?(?:hero[- ]?)?(?:subheadline|subtitle|description|lead)\s+(?:to|as)\s+["']?([^\n"']{2,260})["']?[.!]?$/i], 260); }
function extractCtaText(raw = "") { return extractText(raw, [/(?:ändere|aendere|setze|mach)\s+(?:den\s+|die\s+)?(?:cta|button|knopf|cta[- ]?text|button[- ]?text)\s+(?:auf|zu|in)\s+["„“']?([^\n"„“']{1,100})["„“']?[.!]?$/i, /(?:change|set)\s+(?:the\s+)?(?:cta|button|button text|cta text)\s+(?:to|as)\s+["']?([^\n"']{1,100})["']?[.!]?$/i], 100); }
function extractColumns(raw = "") { const match = /(?:grid|cards?|karten|kacheln)[^\n]{0,50}?(?:auf|in|mit)?\s*(\d)\s*(?:spalten|columns?)/i.exec(raw); return match ? Math.max(1, Math.min(4, Number(match[1]))) : null; }

export function planNaturalEdit(prompt = "", projectAnalysis = null) {
  const raw = clean(prompt, 4000); const text = raw.toLowerCase(); const intensity = detectIntensity(text); const operations = []; const targets = new Set();
  const rocket = includesAny(text, ["rakete", "rocket"]); const smoke = includesAny(text, ["rauch", "smoke", "dampf"]); const hero = includesAny(text, ["hero", "startbereich", "kopfbereich", "hintergrund"]); const nav = includesAny(text, ["navigation", "navbar", "menü", "header"]); const cards = includesAny(text, ["card", "cards", "karte", "karten", "kachel", "kacheln"]); const grid = includesAny(text, ["grid", "spalten", "columns", "karten", "cards"]); const section = includesAny(text, ["section", "sektion", "abschnitt", "bereich"]); const mobile = includesAny(text, ["mobil", "mobile", "smartphone", "handy", "responsive"]); const containment = includesAny(text, ["overflow", "hinausrag", "innerhalb", "begren", "viewport", "seitenbreite", "horizontal"]); const launchScene = rocket || smoke || includesAny(text, ["launch", "startszene", "launch-pad", "launch pad"]);
  const headline = extractHeadline(raw); const subheadline = extractSubheadline(raw); const ctaText = extractCtaText(raw); const columns = extractColumns(raw);
  const rocketSelector = resolveSemanticSelector(projectAnalysis, "rocket", ".rocket-system"); const smokeSelector = resolveSemanticSelector(projectAnalysis, "smoke", ".smoke"); const heroSelector = resolveSemanticSelector(projectAnalysis, "hero", ".hero"); const heroCopySelector = resolveSemanticSelector(projectAnalysis, "hero_copy", ".hero-copy"); const navSelector = resolveSemanticSelector(projectAnalysis, "navigation", ".site-header"); const cardSelector = resolveSemanticSelector(projectAnalysis, "cards", ".card"); const gridSelector = resolveSemanticSelector(projectAnalysis, "grid", ".grid"); const ctaSelector = resolveSemanticSelector(projectAnalysis, "cta", ".cta"); const sectionSelector = resolveSemanticSelector(projectAnalysis, "section", ".section");
  if (headline) { targets.add("headline"); operations.push(operation("h1", "replace_text", headline, "Replace primary headline", "headline")); }
  if (subheadline) { targets.add("subheadline"); operations.push(operation(heroCopySelector, "replace_text", subheadline, "Replace hero supporting text", "subheadline")); }
  if (ctaText) { targets.add("cta"); operations.push(operation(ctaSelector, "replace_text", ctaText, "Replace primary CTA label", "cta")); }
  if (mobile && containment && launchScene) { targets.add("hero"); targets.add("rocket"); targets.add("responsive"); operations.push(operation(heroSelector, "mobile_launch_containment", "strict", "Contain launch scene on mobile", "hero")); }
  if (rocket) { targets.add("rocket"); if (includesAny(text, ["größer", "riesig", "massiv"])) operations.push(operation(rocketSelector, "scale", intensity === "strong" ? 1.6 : intensity === "light" ? 1.15 : 1.35, "Increase rocket size", "rocket")); if (includesAny(text, ["realistisch", "realistischer", "echter"])) { operations.push(operation(rocketSelector, "detail_level", "high", "Increase rocket detail", "rocket")); operations.push(operation(rocketSelector, "lighting", "cinematic", "Improve rocket lighting", "rocket")); } if (includesAny(text, ["schneller", "langsamer"])) operations.push(operation(rocketSelector, "motion_profile", text.includes("langsamer") ? "slower" : "faster", "Adjust launch timing", "rocket")); }
  if (smoke) { targets.add("smoke"); if (includesAny(text, ["mehr", "richtig", "massiv", "dichter", "viel"])) { const density = intensity === "strong" ? 1.8 : intensity === "light" ? 1.15 : 1.45; operations.push(operation(smokeSelector, "density", density, "Increase smoke", "smoke")); operations.push(operation(smokeSelector, "spread", intensity === "strong" ? "wide" : "medium", "Expand smoke", "smoke")); } if (includesAny(text, ["weniger", "reduzier", "leichter"])) operations.push(operation(smokeSelector, "density", 0.7, "Reduce smoke", "smoke")); }
  if (hero) { targets.add("hero"); if (text.includes("dunkler")) operations.push(operation(heroSelector, "brightness", 0.78, "Darken hero", "hero")); if (text.includes("heller")) operations.push(operation(heroSelector, "brightness", 1.12, "Brighten hero", "hero")); if (includesAny(text, ["größer", "höher"])) operations.push(operation(heroSelector, "min_height", "92svh", "Increase hero presence", "hero")); if (includesAny(text, ["zentrier", "mittig", "centered", "center"])) operations.push(operation(heroCopySelector, "text_align", "center", "Center hero content", "hero_copy")); if (includesAny(text, ["linksbündig", "links ausrichten", "left aligned", "align left"])) operations.push(operation(heroCopySelector, "text_align", "left", "Left-align hero content", "hero_copy")); }
  if (nav) { targets.add("navigation"); if (includesAny(text, ["transparent", "durchsichtig"])) operations.push(operation(navSelector, "surface_opacity", 0.72, "Increase header transparency", "navigation")); if (text.includes("dunkler")) operations.push(operation(navSelector, "surface_opacity", 0.94, "Increase header contrast", "navigation")); }
  if (cards) { targets.add("cards"); if (includesAny(text, ["runder", "abgerundet", "runde ecken", "rounded"])) operations.push(operation(cardSelector, "border_radius", intensity === "strong" ? "32px" : "22px", "Round cards", "cards")); if (includesAny(text, ["eckiger", "weniger rund", "kantiger", "square"])) operations.push(operation(cardSelector, "border_radius", "6px", "Square cards", "cards")); if (includesAny(text, ["mehr abstand", "luftiger", "mehr platz", "more spacing"])) operations.push(operation(cardSelector, "padding", intensity === "strong" ? "36px" : "28px", "Increase card spacing", "cards")); }
  if (grid && columns) { targets.add("grid"); operations.push(operation(gridSelector, "columns", columns, "Set grid columns", "grid")); }
  if (section && includesAny(text, ["mehr abstand", "luftiger", "mehr platz", "größerer abstand", "more spacing"])) { targets.add("section"); operations.push(operation(sectionSelector, "vertical_spacing", intensity === "strong" ? "120px" : "88px", "Increase section spacing", "section")); }
  const explicitColor = /#[0-9a-f]{3,8}\b/i.exec(raw); if (explicitColor) { targets.add("theme"); operations.push(operation(":root", "accent_color", explicitColor[0], "Apply accent color", "theme")); }
  return { version: 3, mode: "natural-edit-plan", prompt: raw, intensity, targets: [...targets], operations, project_aware: Boolean(projectAnalysis), resolved_selectors: projectAnalysis?.semantic || null, requires_interpretation: operations.length === 0, safety: { production_deploy: false, active_project_only: true, create_new_project: false, standalone_image_generation: false } };
}
