export const SYNTROPIC_SITE = String.raw`<!doctype html>
<html lang="de">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="theme-color" content="#06070a" />
  <meta name="description" content="SYNTROPIC entwickelt Unternehmen als intelligente, integrierte Business-Ökosysteme." />
  <title>SYNTROPIC — Business-Ökosysteme syntropisieren</title>
  <style>
    :root{--bg:#06070a;--bg2:#0a0c12;--card:rgba(255,255,255,.045);--line:rgba(255,255,255,.1);--text:#f7f8fb;--muted:#9aa2b2;--violet:#8b5cf6;--violet2:#b79cff;--blue:#5f7cff;--success:#8ef0c1;--shadow:0 30px 90px rgba(0,0,0,.38)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(900px 600px at 70% -5%,rgba(111,73,255,.12),transparent 60%),var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;line-height:1.5;overflow-x:hidden}
    a{color:inherit;text-decoration:none}button{font:inherit}.wrap{width:min(1180px,calc(100% - 40px));margin:auto}.eyebrow{text-transform:uppercase;letter-spacing:.2em;font-size:.72rem;color:#aeb5c3}.section{padding:120px 0;position:relative}.section h2{font-size:clamp(2.2rem,5vw,4.8rem);line-height:.98;letter-spacing:-.055em;margin:14px 0 26px}.section p.lead{max-width:760px;color:#b6bdc9;font-size:clamp(1.05rem,1.8vw,1.35rem)}
    .nav{position:fixed;z-index:30;top:14px;left:50%;transform:translateX(-50%);width:min(1180px,calc(100% - 24px));display:flex;align-items:center;justify-content:space-between;padding:12px 16px;border:1px solid rgba(255,255,255,.09);background:rgba(8,9,13,.7);backdrop-filter:blur(20px);border-radius:18px;box-shadow:0 16px 50px rgba(0,0,0,.18)}
    .brand{display:flex;align-items:center;gap:11px;font-weight:700;letter-spacing:.16em;font-size:.9rem}.mark{width:28px;height:28px;border:1px solid rgba(184,156,255,.65);border-radius:8px;display:grid;place-items:center;transform:rotate(45deg);box-shadow:0 0 24px rgba(139,92,246,.18)}.mark:before{content:"S";transform:rotate(-45deg);font-weight:800;color:#c6b4ff;font-size:.8rem}.navlinks{display:flex;gap:24px;font-size:.88rem;color:#aeb5c3}.navlinks a:hover{color:#fff}.btn{border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.035);padding:11px 16px;border-radius:12px;display:inline-flex;gap:10px;align-items:center;transition:.25s ease;cursor:pointer}.btn:hover{transform:translateY(-2px);border-color:rgba(183,156,255,.55);background:rgba(139,92,246,.1)}.btn.primary{background:linear-gradient(135deg,#7650ff,#9b72ff);border-color:transparent;color:white;box-shadow:0 12px 35px rgba(117,80,255,.25)}
    .hero{min-height:100vh;display:grid;align-items:center;padding:150px 0 70px;position:relative}.hero:before{content:"";position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.02) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.02) 1px,transparent 1px);background-size:58px 58px;mask-image:linear-gradient(to bottom,rgba(0,0,0,.6),transparent 88%);pointer-events:none}.hero-grid{display:grid;grid-template-columns:1.18fr .82fr;gap:60px;align-items:center}.hero h1{font-size:clamp(3.8rem,8vw,8.3rem);line-height:.84;letter-spacing:-.075em;margin:18px 0 28px;max-width:900px}.hero h1 span{background:linear-gradient(110deg,#fff 8%,#c5b5ff 53%,#6f7fff);-webkit-background-clip:text;background-clip:text;color:transparent}.hero .sub{font-size:clamp(1.12rem,2vw,1.45rem);color:#aeb5c3;max-width:690px}.hero-actions{display:flex;gap:12px;margin-top:34px;flex-wrap:wrap}.proof{display:flex;gap:20px;align-items:center;margin-top:38px;color:#7f8796;font-size:.82rem}.proof b{color:#d9dce3;font-weight:600}.orb{aspect-ratio:1;position:relative;display:grid;place-items:center}.orb-core{width:66%;aspect-ratio:1;border-radius:28%;transform:rotate(45deg);border:1px solid rgba(171,144,255,.42);background:linear-gradient(145deg,rgba(145,102,255,.16),rgba(45,51,80,.02));box-shadow:inset 0 0 60px rgba(114,76,255,.08),0 0 90px rgba(92,61,255,.12);animation:float 7s ease-in-out infinite}.orb-core:before,.orb-core:after{content:"";position:absolute;inset:14%;border:1px solid rgba(255,255,255,.16);border-radius:22%}.orb-core:after{inset:30%;background:radial-gradient(circle at 30% 30%,rgba(255,255,255,.25),rgba(123,84,255,.1));box-shadow:0 0 55px rgba(123,84,255,.22)}.ring{position:absolute;width:92%;height:28%;border:1px solid rgba(137,103,255,.25);border-radius:50%;bottom:7%;box-shadow:0 0 50px rgba(93,64,255,.13)}.ring.r2{width:72%;bottom:12%;opacity:.7}.orbit-dot{position:absolute;width:6px;height:6px;border-radius:50%;background:#af91ff;box-shadow:0 0 16px #9a76ff;animation:orbit 9s linear infinite;transform-origin:160px 0}.hero-note{position:absolute;right:4%;bottom:7%;font-size:.72rem;color:#5e6572;letter-spacing:.15em;text-transform:uppercase}
    @keyframes float{0%,100%{transform:rotate(45deg) translateY(0)}50%{transform:rotate(45deg) translate(-9px,9px)}}@keyframes orbit{to{transform:rotate(360deg) translateX(160px)}}
    .statement{padding:90px 0 130px}.statement-grid{display:grid;grid-template-columns:.75fr 1.25fr;gap:50px}.quote{font-size:clamp(2.4rem,5.6vw,6rem);letter-spacing:-.06em;line-height:.98}.quote em{font-style:normal;color:#9e83ff}.statement-copy{align-self:end;color:#aab1bf;font-size:1.1rem;max-width:600px}
    .chaos-stage{margin-top:62px;border:1px solid var(--line);border-radius:28px;min-height:540px;background:radial-gradient(circle at 50% 50%,rgba(117,80,255,.08),transparent 45%),rgba(255,255,255,.018);overflow:hidden;position:relative;box-shadow:var(--shadow)}.chaos-label{position:absolute;top:24px;left:28px;color:#8e96a5;font-size:.78rem;letter-spacing:.14em;text-transform:uppercase}.chaos-label.right{left:auto;right:28px}.node{position:absolute;border:1px solid rgba(255,255,255,.13);background:rgba(11,12,18,.78);backdrop-filter:blur(12px);border-radius:14px;padding:13px 16px;color:#c8cdd6;font-size:.82rem;transition:1.2s cubic-bezier(.2,.8,.2,1);box-shadow:0 14px 34px rgba(0,0,0,.25)}.node:before{content:"";width:7px;height:7px;border-radius:50%;background:#8b5cf6;display:inline-block;margin-right:8px;box-shadow:0 0 12px rgba(139,92,246,.6)}.chaos-stage.syntropic .node{left:50%!important;top:50%!important;transform:translate(-50%,-50%) rotate(0)!important;border-color:rgba(161,131,255,.34)}.chaos-stage.syntropic .node:nth-of-type(2){transform:translate(-180%,-180%)!important}.chaos-stage.syntropic .node:nth-of-type(3){transform:translate(70%,-180%)!important}.chaos-stage.syntropic .node:nth-of-type(4){transform:translate(-185%,85%)!important}.chaos-stage.syntropic .node:nth-of-type(5){transform:translate(90%,85%)!important}.chaos-stage.syntropic .node:nth-of-type(6){transform:translate(-50%,-50%) scale(1.18)!important;background:rgba(127,87,255,.15)}.chaos-line{position:absolute;height:1px;background:linear-gradient(90deg,transparent,rgba(131,93,255,.32),transparent);width:60%;left:20%;top:50%;opacity:0;transition:1s}.chaos-stage.syntropic .chaos-line{opacity:1}.toggle-row{display:flex;justify-content:center;margin-top:22px}.seg{display:inline-flex;border:1px solid var(--line);border-radius:14px;padding:5px;background:#090b10}.seg button{border:0;background:transparent;color:#8f97a6;padding:10px 16px;border-radius:10px;cursor:pointer}.seg button.active{background:#16121f;color:#eee6ff;box-shadow:inset 0 0 0 1px rgba(153,116,255,.23)}
    .problem-grid,.benefit-grid,.products{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:48px}.glass{border:1px solid var(--line);background:linear-gradient(180deg,rgba(255,255,255,.047),rgba(255,255,255,.018));border-radius:22px;padding:28px;min-height:220px;box-shadow:0 24px 70px rgba(0,0,0,.18);transition:.3s}.glass:hover{transform:translateY(-5px);border-color:rgba(170,145,255,.35)}.icon{width:44px;height:44px;border-radius:12px;display:grid;place-items:center;background:rgba(139,92,246,.08);border:1px solid rgba(139,92,246,.18);margin-bottom:28px;color:#bda9ff}.glass h3{margin:0 0 10px;font-size:1.15rem}.glass p{margin:0;color:#929aa9}.icon svg{width:22px;height:22px;stroke:currentColor;fill:none;stroke-width:1.7}
    .solution{display:grid;grid-template-columns:1fr 1fr;gap:54px;align-items:center}.system-card{border:1px solid var(--line);border-radius:28px;padding:24px;background:rgba(255,255,255,.025);box-shadow:var(--shadow)}.system-map{position:relative;aspect-ratio:1.05;background:radial-gradient(circle at 50% 50%,rgba(139,92,246,.12),transparent 48%);display:grid;place-items:center}.hub{width:150px;height:150px;border-radius:50%;display:grid;place-items:center;text-align:center;background:radial-gradient(circle,#241941,#0c0d13 70%);border:1px solid rgba(166,135,255,.42);box-shadow:0 0 70px rgba(122,80,255,.16);font-weight:650}.sat{position:absolute;padding:10px 13px;border-radius:10px;border:1px solid rgba(255,255,255,.12);background:#0c0e14;color:#b8bfcb;font-size:.76rem}.sat.s1{top:8%;left:38%}.sat.s2{top:24%;right:5%}.sat.s3{bottom:23%;right:4%}.sat.s4{bottom:7%;left:38%}.sat.s5{bottom:23%;left:5%}.sat.s6{top:24%;left:4%}.system-map:before,.system-map:after{content:"";position:absolute;width:70%;height:70%;border-radius:50%;border:1px dashed rgba(144,108,255,.18);animation:spin 24s linear infinite}.system-map:after{width:48%;height:48%;animation-direction:reverse;animation-duration:15s}@keyframes spin{to{transform:rotate(360deg)}}
    .product-main{grid-column:span 2;min-height:430px;padding:38px;position:relative;overflow:hidden}.product-main:after{content:"FullAutoBIZ";position:absolute;right:-16px;bottom:-30px;font-size:clamp(4rem,9vw,8rem);font-weight:800;letter-spacing:-.07em;color:rgba(255,255,255,.025)}.product-main h3{font-size:clamp(2rem,4vw,3.4rem);letter-spacing:-.04em}.chips{display:flex;gap:8px;flex-wrap:wrap;margin-top:26px}.chip{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.03);border-radius:999px;padding:8px 11px;color:#aab1bd;font-size:.76rem}.coming{display:grid;align-content:end;min-height:430px}.coming .big{font-size:3.3rem;color:#2d3038;font-weight:700;letter-spacing:-.05em}
    .tech-band{border-top:1px solid var(--line);border-bottom:1px solid var(--line);background:linear-gradient(90deg,rgba(255,255,255,.02),rgba(110,74,255,.05),rgba(255,255,255,.02))}.tech-grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:60px;align-items:center}.tech-lockup{font-size:clamp(2.3rem,4.5vw,4.8rem);font-weight:720;letter-spacing:-.06em}.tech-lockup span{display:block;color:#8a92a0;font-size:.34em;letter-spacing:.18em;text-transform:uppercase;margin-bottom:12px}.tech-list{display:grid;grid-template-columns:1fr 1fr;gap:14px}.tech-pill{padding:18px 20px;border:1px solid var(--line);border-radius:14px;color:#aeb5c2;background:rgba(255,255,255,.02)}
    .flow{margin-top:60px;display:grid;grid-template-columns:repeat(5,1fr);gap:10px;position:relative}.flow-step{padding:24px 18px;border:1px solid var(--line);border-radius:18px;background:#0a0c11;min-height:180px}.flow-step span{font-size:.7rem;color:#6f7786;letter-spacing:.14em}.flow-step h4{font-size:1.05rem;margin:40px 0 8px}.flow-step p{font-size:.84rem;color:#8f97a5;margin:0}.flow-step.active{border-color:rgba(160,128,255,.4);background:linear-gradient(180deg,rgba(139,92,246,.1),rgba(255,255,255,.018))}.flow-step.active h4{color:#cab9ff}
    .architecture{display:grid;grid-template-columns:.8fr 1.2fr;gap:42px;margin-top:54px}.arch-stack{display:grid;gap:10px}.layer{border:1px solid var(--line);border-radius:14px;padding:18px 20px;display:flex;justify-content:space-between;align-items:center;background:rgba(255,255,255,.02)}.layer b{font-size:.95rem}.layer span{color:#777f8e;font-size:.76rem}.arch-note{padding:34px;border-radius:24px;background:linear-gradient(135deg,rgba(139,92,246,.12),rgba(255,255,255,.02));border:1px solid rgba(151,118,255,.22);display:flex;flex-direction:column;justify-content:flex-end}.arch-note strong{font-size:clamp(1.8rem,4vw,3.2rem);letter-spacing:-.045em;line-height:1}.arch-note p{color:#9ca4b2}
    .faq{max-width:900px;margin:48px auto 0}.faq-item{border-top:1px solid var(--line)}.faq-q{width:100%;display:flex;justify-content:space-between;align-items:center;padding:24px 0;background:none;border:0;color:#e9ebef;text-align:left;cursor:pointer;font-size:1.02rem}.faq-a{max-height:0;overflow:hidden;color:#949caa;transition:.35s ease}.faq-item.open .faq-a{max-height:180px;padding-bottom:24px}.faq-q span:last-child{transition:.3s}.faq-item.open .faq-q span:last-child{transform:rotate(45deg)}
    .cta{padding:130px 0}.cta-box{border:1px solid rgba(172,143,255,.26);border-radius:32px;padding:70px;background:radial-gradient(600px 250px at 50% 0%,rgba(128,84,255,.16),transparent 70%),#090a0f;text-align:center;box-shadow:0 35px 90px rgba(0,0,0,.35)}.cta-box h2{max-width:900px;margin:10px auto 24px}.cta-box p{max-width:650px;margin:0 auto 30px;color:#9ea6b4}.footer{border-top:1px solid var(--line);padding:34px 0 50px;color:#777f8d}.footer-row{display:flex;justify-content:space-between;gap:24px;align-items:center}.footer nav{display:flex;gap:18px;font-size:.82rem}
    .reveal{opacity:0;transform:translateY(24px);transition:.8s cubic-bezier(.2,.8,.2,1)}.reveal.in{opacity:1;transform:none}.progress{position:fixed;z-index:40;left:0;top:0;height:2px;background:linear-gradient(90deg,#7b5cff,#b49aff);width:0}.cursor-glow{position:fixed;pointer-events:none;width:260px;height:260px;border-radius:50%;background:radial-gradient(circle,rgba(120,80,255,.08),transparent 65%);transform:translate(-50%,-50%);z-index:1}
    @media(max-width:900px){.navlinks{display:none}.hero-grid,.solution,.tech-grid,.statement-grid,.architecture{grid-template-columns:1fr}.orb{max-width:560px;margin:auto}.problem-grid,.benefit-grid,.products{grid-template-columns:1fr}.product-main{grid-column:auto}.flow{grid-template-columns:1fr 1fr}.section{padding:90px 0}.hero h1{font-size:clamp(3.5rem,15vw,6rem)}.statement{padding-top:50px}.cta-box{padding:46px 24px}}
    @media(max-width:600px){.wrap{width:min(100% - 28px,1180px)}.hero{padding-top:125px}.orb{display:none}.hero-grid{grid-template-columns:1fr}.proof{align-items:flex-start;flex-direction:column;gap:5px}.flow{grid-template-columns:1fr}.tech-list{grid-template-columns:1fr}.cta-box{border-radius:22px}.footer-row{align-items:flex-start;flex-direction:column}.nav .btn{padding:9px 12px;font-size:.78rem}.chaos-stage{min-height:470px}}
  </style>
</head>
<body>
<div class="progress" id="progress"></div><div class="cursor-glow" id="glow"></div>
<header class="nav"><a class="brand" href="#top"><span class="mark"></span>SYNTROPIC</a><nav class="navlinks"><a href="#vision">Vision</a><a href="#syntropie">Syntropie</a><a href="#produkte">Systeme</a><a href="#technologie">Technologie</a></nav><a class="btn" href="#kontakt">Systemgespräch <span>↗</span></a></header>
<main id="top">
<section class="hero"><div class="wrap hero-grid"><div><div class="eyebrow reveal">Business Systems Engineering</div><h1 class="reveal">Wir bauen keine Webseiten.<br><span>Wir entwickeln Unternehmen als intelligente Systeme.</span></h1><p class="sub reveal">SYNTROPIC transformiert fragmentierte Prozesse in integrierte, lernende und weitgehend autonome Business-Ökosysteme.</p><div class="hero-actions reveal"><a class="btn primary" href="#kontakt">Jetzt syntropisieren <span>↗</span></a><a class="btn" href="#syntropie">System verstehen <span>↓</span></a></div><div class="proof reveal"><b>SYNTROPIC</b><span>Operative Business-Systeme</span><span>•</span><span>Technology by RIOSYSTEMS</span></div></div><div class="orb reveal"><div class="ring"></div><div class="ring r2"></div><div class="orb-core"></div><div class="orbit-dot"></div></div></div><div class="hero-note">Order → Integration → Intelligence → Evolution</div></section>
<section class="statement" id="vision"><div class="wrap statement-grid"><div class="eyebrow reveal">Eine neue Kategorie</div><div><div class="quote reveal">Unternehmen sind heute Sammlungen von Tools. <em>Wir machen daraus Systeme.</em></div><p class="statement-copy reveal">Nicht mehr Software neben Software. Nicht mehr Abteilungen als Inseln. Nicht mehr Menschen als Schnittstellen zwischen fragmentierten Prozessen. SYNTROPIC entwirft die operative Architektur eines Unternehmens neu.</p></div></div></section>
<section class="section" id="syntropie"><div class="wrap"><div class="eyebrow reveal">Was bedeutet Syntropisierung?</div><h2 class="reveal">Vom betrieblichen Chaos<br>zur intelligenten Ordnung.</h2><p class="lead reveal">Syntropie ist die Gegenbewegung zur Fragmentierung: Ordnung statt Chaos. Integration statt Insellösungen. Intelligenz statt manueller Übergaben. Evolution statt Verwaltung.</p><div class="chaos-stage reveal" id="chaos"><div class="chaos-label">Fragmentiert</div><div class="chaos-label right">Syntropisch</div><div class="chaos-line"></div><div class="node" style="left:8%;top:22%;transform:rotate(-4deg)">CRM</div><div class="node" style="left:66%;top:16%;transform:rotate(3deg)">Marketing</div><div class="node" style="left:16%;top:68%;transform:rotate(5deg)">Support</div><div class="node" style="left:70%;top:68%;transform:rotate(-3deg)">Daten</div><div class="node" style="left:43%;top:38%;transform:rotate(2deg)">Operations</div><div class="node" style="left:44%;top:58%;transform:rotate(-2deg)">SYNTROPIC CORE</div></div><div class="toggle-row"><div class="seg"><button class="active" data-mode="chaos">Chaos</button><button data-mode="syntropic">Syntropie</button></div></div></div></section>
<section class="section"><div class="wrap"><div class="eyebrow reveal">Das Problem</div><h2 class="reveal">Die meisten Unternehmen skalieren<br>ihre Komplexität.</h2><div class="problem-grid"><article class="glass reveal"><div class="icon"><svg viewBox="0 0 24 24"><path d="M4 7h6v6H4zM14 4h6v6h-6zM14 14h6v6h-6zM4 17h6"/></svg></div><h3>Tool-Fragmente</h3><p>CRM, Marketing, Support, Daten und Kommunikation existieren nebeneinander, statt als gemeinsames System.</p></article><article class="glass reveal"><div class="icon"><svg viewBox="0 0 24 24"><path d="M5 12h14M12 5v14M7 7l10 10M17 7 7 17"/></svg></div><h3>Manuelle Übergaben</h3><p>Menschen werden zu Schnittstellen. Wissen wandert per Copy & Paste, Meetings und Erinnerung.</p></article><article class="glass reveal"><div class="icon"><svg viewBox="0 0 24 24"><path d="M4 18 9 13l3 3 8-10M17 6h3v3"/></svg></div><h3>Wachstum = Reibung</h3><p>Mehr Kunden erzeugen mehr Prozesse, mehr Personalbedarf und mehr operative Unschärfe.</p></article></div></div></section>
<section class="section"><div class="wrap solution"><div><div class="eyebrow reveal">Unsere Lösung</div><h2 class="reveal">Ein Unternehmen.<br>Ein Nervensystem.</h2><p class="lead reveal">Wir verbinden digitale Touchpoints, Daten, Automationen und KI zu einer konsistenten Business-Architektur. Das Ergebnis ist kein Toolstack. Es ist ein System, das wahrnimmt, entscheidet, ausführt und lernt.</p><div class="hero-actions reveal"><a class="btn primary" href="#produkte">Produktfamilien ansehen</a></div></div><div class="system-card reveal"><div class="system-map"><div class="hub">Business<br>Intelligence<br>Core</div><div class="sat s1">Website</div><div class="sat s2">Lead Engine</div><div class="sat s3">CRM</div><div class="sat s4">Operations</div><div class="sat s5">Support AI</div><div class="sat s6">Data Layer</div></div></div></div></section>
<section class="section" id="produkte"><div class="wrap"><div class="eyebrow reveal">Produktfamilien</div><h2 class="reveal">Systeme statt Einzelleistungen.</h2><div class="products"><article class="glass product-main reveal"><div class="eyebrow">01 — FullAutoBIZ</div><h3>Nahezu vollständig automatisierte Unternehmen.</h3><p class="lead">FullAutoBIZ verbindet Marktauftritt, Kundengewinnung, CRM, Support, interne KI, Daten und Business-Workflows zu einer operativen Einheit. Module können einzeln starten und später in das Gesamtsystem wachsen.</p><div class="chips"><span class="chip">Premium Website</span><span class="chip">CRM</span><span class="chip">KI-Support</span><span class="chip">Interne KI</span><span class="chip">Marketing-Automatisierung</span><span class="chip">Leadgenerierung</span><span class="chip">Produktgenerierung</span><span class="chip">Datenstrukturen</span><span class="chip">Business Workflows</span></div></article><article class="glass coming reveal"><div class="big">02+</div><h3>Nächste Systeme</h3><p>Weitere Produktfamilien befinden sich in Entwicklung.</p><span class="chip" style="width:max-content;margin-top:16px">Coming Soon</span></article></div></div></section>
<section class="section tech-band" id="technologie"><div class="wrap tech-grid"><div class="tech-lockup reveal"><span>Muttergesellschaft & Technologie</span>RIOSYSTEMS</div><div><p class="lead reveal">Forschung, KI-Systeme und Basistechnologien entstehen im technologischen Fundament von RIOSYSTEMS. SYNTROPIC überführt diese Fähigkeiten in marktfähige operative Business-Systeme.</p><div class="tech-list reveal"><div class="tech-pill">AI Systems</div><div class="tech-pill">Data Architecture</div><div class="tech-pill">Automation Layer</div><div class="tech-pill">Business Intelligence</div></div></div></div></section>
<section class="section"><div class="wrap"><div class="eyebrow reveal">Transformation</div><h2 class="reveal">Von Prozesslast zu Systemintelligenz.</h2><p class="lead reveal">Die Transformation erfolgt nicht durch einen Big Bang. Sie wird als kontrollierter Systemumbau orchestriert.</p><div class="flow"><div class="flow-step reveal"><span>01</span><h4>Mapping</h4><p>Prozesse, Daten, Rollen und Engpässe sichtbar machen.</p></div><div class="flow-step reveal"><span>02</span><h4>Reduktion</h4><p>Redundanzen entfernen und Schnittstellen vereinfachen.</p></div><div class="flow-step active reveal"><span>03</span><h4>Integration</h4><p>Systeme und Daten zu einer Architektur verbinden.</p></div><div class="flow-step reveal"><span>04</span><h4>Intelligenz</h4><p>Entscheidungen und Ausführung mit KI anreichern.</p></div><div class="flow-step reveal"><span>05</span><h4>Evolution</h4><p>Das Unternehmen wird messbar, lernend und adaptiv.</p></div></div></div></section>
<section class="section"><div class="wrap"><div class="eyebrow reveal">Vorteile</div><h2 class="reveal">Weniger Reibung.<br>Mehr Systemleistung.</h2><div class="benefit-grid"><article class="glass reveal"><h3>Operative Klarheit</h3><p>Ein konsistentes Systemmodell statt verteilter Verantwortlichkeiten und Schattenprozesse.</p></article><article class="glass reveal"><h3>Skalierbarkeit</h3><p>Wachstum muss nicht proportional mehr manuelle Koordination erzeugen.</p></article><article class="glass reveal"><h3>Geschwindigkeit</h3><p>Daten, Entscheidungen und Aktionen bewegen sich schneller durch das Unternehmen.</p></article><article class="glass reveal"><h3>Lernfähigkeit</h3><p>Systeme erzeugen Feedback, das Prozesse und Entscheidungen kontinuierlich verbessert.</p></article><article class="glass reveal"><h3>Transparenz</h3><p>Relevante Daten werden strukturiert und für operative Entscheidungen nutzbar.</p></article><article class="glass reveal"><h3>Autonomie</h3><p>Wiederkehrende Abläufe werden zunehmend ohne manuelle Intervention ausführbar.</p></article></div></div></section>
<section class="section"><div class="wrap"><div class="eyebrow reveal">Referenzarchitektur</div><h2 class="reveal">Die Architektur hinter<br>einem syntropischen Unternehmen.</h2><div class="architecture"><div class="arch-stack reveal"><div class="layer"><b>Experience Layer</b><span>Web · Sales · Support</span></div><div class="layer"><b>Automation Layer</b><span>Triggers · Workflows · Agents</span></div><div class="layer"><b>Intelligence Layer</b><span>AI · Decisions · Knowledge</span></div><div class="layer"><b>Data Layer</b><span>CRM · Events · Business Data</span></div><div class="layer"><b>Infrastructure Layer</b><span>Cloud · Security · Observability</span></div></div><aside class="arch-note reveal"><div class="eyebrow">Prinzip</div><strong>Jede Ebene kennt ihren Zweck. Jede Ebene spricht mit der nächsten.</strong><p>So entsteht aus einzelnen Technologien ein kohärentes operatives System.</p></aside></div></div></section>
<section class="section"><div class="wrap"><div class="eyebrow reveal">FAQ</div><h2 class="reveal">Die wichtigsten Fragen.</h2><div class="faq"><div class="faq-item reveal"><button class="faq-q"><span>Ist SYNTROPIC eine Agentur?</span><span>＋</span></button><div class="faq-a">Nein. SYNTROPIC entwickelt Business-Ökosysteme. Webseiten, CRM, Automationen oder KI sind dabei mögliche Systemmodule, aber nicht die eigentliche Kategorie unseres Angebots.</div></div><div class="faq-item reveal"><button class="faq-q"><span>Muss ein Unternehmen komplett neu aufgebaut werden?</span><span>＋</span></button><div class="faq-a">Nein. Bestehende Strukturen können analysiert, reduziert, verbunden und schrittweise syntropisiert werden. Der Einstieg kann auch über einzelne Module erfolgen.</div></div><div class="faq-item reveal"><button class="faq-q"><span>Für wen ist FullAutoBIZ gedacht?</span><span>＋</span></button><div class="faq-a">Für Unternehmer, Startups, Mittelstand, Wachstumsunternehmen, Investoren und digitale Unternehmen, die operative Skalierung nicht mit proportional steigender Komplexität bezahlen wollen.</div></div><div class="faq-item reveal"><button class="faq-q"><span>Was ist das Ziel einer Syntropisierung?</span><span>＋</span></button><div class="faq-a">Ein integriertes, messbares und zunehmend intelligentes Unternehmen, in dem Daten, Prozesse, Systeme und Menschen nicht gegeneinander arbeiten, sondern als ein zusammenhängendes Ökosystem.</div></div></div></div></section>
<section class="cta" id="kontakt"><div class="wrap"><div class="cta-box reveal"><div class="eyebrow">Systemgespräch</div><h2>Wenn dein Unternehmen heute aus Tools besteht, kann es morgen als System funktionieren.</h2><p>Wir analysieren, wo Fragmentierung entsteht, welche Strukturen verbunden werden müssen und welche Form von Syntropisierung wirtschaftlich sinnvoll ist.</p><a class="btn primary" href="mailto:hello@syntropic.systems">Transformation besprechen <span>↗</span></a></div></div></section>
</main>
<footer class="footer"><div class="wrap footer-row"><div class="brand"><span class="mark"></span>SYNTROPIC</div><nav><a href="#vision">Vision</a><a href="#produkte">FullAutoBIZ</a><a href="#technologie">Technologie</a><a href="#kontakt">Kontakt</a></nav><div>© 2026 SYNTROPIC · A RIOSYSTEMS company</div></div></footer>
<script>
  var reveal=function(){document.querySelectorAll('.reveal').forEach(function(el){var r=el.getBoundingClientRect();if(r.top<window.innerHeight*0.9)el.classList.add('in')})};reveal();window.addEventListener('scroll',function(){reveal();var d=document.documentElement;document.getElementById('progress').style.width=((d.scrollTop/(d.scrollHeight-d.clientHeight))*100)+'%'});
  document.querySelectorAll('.seg button').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.seg button').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');document.getElementById('chaos').classList.toggle('syntropic',btn.dataset.mode==='syntropic')})});
  document.querySelectorAll('.faq-q').forEach(function(q){q.addEventListener('click',function(){q.parentElement.classList.toggle('open')})});
  var glow=document.getElementById('glow');window.addEventListener('pointermove',function(e){glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});
  var chaos=document.getElementById('chaos');var chaosObserver=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting)setTimeout(function(){chaos.classList.add('syntropic');document.querySelectorAll('.seg button').forEach(function(b){b.classList.toggle('active',b.dataset.mode==='syntropic')})},700)})},{threshold:.45});chaosObserver.observe(chaos);
</script>
</body>
</html>`;
