export const SYNTROPIC_SITE = String.raw`<!doctype html>
<html lang="de">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta name="theme-color" content="#050607" />
  <meta name="description" content="SYNTROPIC entwickelt Unternehmen als integrierte, intelligente und zunehmend autonome Business-Systeme." />
  <meta property="og:title" content="SYNTROPIC | Intelligent Business Systems" />
  <meta property="og:description" content="Wir bauen keine Webseiten. Wir entwickeln Unternehmen als intelligente Systeme." />
  <meta property="og:type" content="website" />
  <title>SYNTROPIC | Intelligent Business Systems</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=Inter:wght@400;500;600&display=swap');
    :root{
      --bg:#050607;--panel:#090b0d;--panel2:#0c0f12;--text:#f4f5f6;--muted:#949ba3;--dim:#5f666e;
      --line:rgba(255,255,255,.115);--line2:rgba(255,255,255,.06);--violet:#9a82ff;--violet2:#6e58d9;
      --signal:#c7baff;--ok:#a8edc8;--mono:"IBM Plex Mono","SFMono-Regular",Consolas,monospace;--sans:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif
    }
    *{box-sizing:border-box}html{scroll-behavior:smooth;background:var(--bg)}body{margin:0;background:var(--bg);color:var(--text);font-family:var(--sans);line-height:1.55;overflow-x:hidden}
    body:before{content:"";position:fixed;inset:0;pointer-events:none;z-index:80;opacity:.17;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.85' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.2'/%3E%3C/svg%3E")}
    a{color:inherit;text-decoration:none}button,input,textarea{font:inherit}.wrap{width:min(1240px,calc(100% - 48px));margin:auto}.mono{font-family:var(--mono)}
    .kicker{font:500 .68rem/1.4 var(--mono);letter-spacing:.19em;text-transform:uppercase;color:#979ea7}.kicker b{color:var(--signal);font-weight:500}.section{position:relative;padding:132px 0;border-top:1px solid var(--line2)}
    h1,h2,h3,p{margin-top:0}h2{font-size:clamp(2.7rem,5.7vw,6.5rem);line-height:.91;letter-spacing:-.065em;font-weight:500;margin:18px 0 28px;max-width:1080px}p.lead{font-size:clamp(1rem,1.55vw,1.23rem);color:#aeb4bc;max-width:760px}
    .progress{position:fixed;left:0;top:0;height:2px;background:var(--signal);z-index:100;width:0;box-shadow:0 0 14px rgba(154,130,255,.55)}
    .nav{position:fixed;top:0;left:0;right:0;height:70px;z-index:70;border-bottom:1px solid var(--line);background:rgba(5,6,7,.78);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
    .navin{height:100%;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:20px}.brand{display:flex;align-items:center;gap:12px;font:600 .75rem/1 var(--mono);letter-spacing:.18em}.sigil{width:30px;height:30px;position:relative;border:1px solid rgba(199,186,255,.48)}.sigil:before,.sigil:after{content:"";position:absolute;background:var(--signal)}.sigil:before{width:1px;height:20px;left:14px;top:4px;transform:rotate(45deg)}.sigil:after{height:1px;width:20px;top:14px;left:4px;transform:rotate(45deg)}
    .navlinks{display:flex;align-items:center;gap:26px;font:500 .65rem/1 var(--mono);letter-spacing:.13em;text-transform:uppercase;color:#8f969f}.navlinks a{transition:.2s}.navlinks a:hover{color:#fff}.navright{display:flex;justify-content:flex-end}.navcta,.btn{display:inline-flex;align-items:center;justify-content:center;gap:11px;border:1px solid var(--line);background:#080a0c;color:#e8e9ea;min-height:40px;padding:0 15px;font:500 .67rem/1 var(--mono);letter-spacing:.12em;text-transform:uppercase;cursor:pointer;transition:.22s}.navcta:hover,.btn:hover{background:#f2f2f2;color:#08090a;border-color:#f2f2f2}.btn.signal{border-color:rgba(199,186,255,.42);color:#ddd7ff}.btn.signal:hover{background:var(--signal);color:#08090a}.btn.ghost{background:transparent}
    .hero{min-height:100svh;position:relative;display:flex;align-items:flex-end;padding:156px 0 76px;border-bottom:1px solid var(--line)}#heroCanvas{position:absolute;inset:0;width:100%;height:100%;opacity:.72}.heroShade{position:absolute;inset:0;background:linear-gradient(90deg,rgba(5,6,7,.96) 0%,rgba(5,6,7,.83) 42%,rgba(5,6,7,.28) 74%,rgba(5,6,7,.7) 100%),linear-gradient(0deg,#050607 0%,transparent 30%);pointer-events:none}
    .heroGrid{position:relative;z-index:2;display:grid;grid-template-columns:minmax(0,1.2fr) minmax(280px,.55fr);gap:64px;align-items:end}.hero h1{font-size:clamp(4.1rem,8.3vw,9.5rem);line-height:.78;letter-spacing:-.075em;font-weight:500;margin:22px 0 34px;max-width:1030px}.hero h1 .mute{color:#6f747a}.hero h1 .accent{color:var(--signal)}.heroText{max-width:720px;color:#adb3ba;font-size:clamp(1.05rem,1.55vw,1.32rem);margin-bottom:34px}.heroActions{display:flex;gap:10px;flex-wrap:wrap}
    .telemetry{border-left:1px solid var(--line);padding-left:24px;font:400 .66rem/1.75 var(--mono);letter-spacing:.09em;color:#777e86;text-transform:uppercase}.telemetry .row{display:flex;justify-content:space-between;gap:22px;border-bottom:1px solid var(--line2);padding:8px 0}.telemetry b{font-weight:500;color:#c7ccd1}.pulse{width:7px;height:7px;border-radius:50%;background:var(--ok);box-shadow:0 0 13px rgba(168,237,200,.55);display:inline-block;margin-right:8px}
    .scrollCue{position:absolute;right:24px;bottom:24px;font:400 .62rem/1 var(--mono);letter-spacing:.15em;color:#5e656d;transform:rotate(90deg);transform-origin:right center;text-transform:uppercase}
    .manifest{padding:160px 0}.manifestGrid{display:grid;grid-template-columns:.42fr 1.58fr;gap:70px}.manifestQuote{font-size:clamp(2.9rem,5.3vw,6.4rem);line-height:.95;letter-spacing:-.061em;font-weight:500}.manifestQuote .violet{color:var(--signal)}.manifestCopy{max-width:660px;color:#969da5;font-size:1.08rem;margin-top:36px}
    .systemStrip{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--line);margin-top:76px}.systemStrip div{padding:22px 20px;border-right:1px solid var(--line);min-height:118px}.systemStrip div:last-child{border-right:0}.systemStrip span{display:block;font:500 .61rem/1.2 var(--mono);letter-spacing:.14em;color:#686f77;text-transform:uppercase;margin-bottom:28px}.systemStrip strong{font-weight:500;font-size:1.02rem}
    .split{display:grid;grid-template-columns:.8fr 1.2fr;gap:72px;align-items:start}.stickyIntro{position:sticky;top:110px}.stickyIntro h2{font-size:clamp(2.6rem,4.8vw,5.2rem)}
    .problemList{border-top:1px solid var(--line)}.problem{display:grid;grid-template-columns:74px 1fr;gap:20px;padding:34px 0;border-bottom:1px solid var(--line)}.problem .num{font:500 .65rem/1 var(--mono);letter-spacing:.14em;color:#626971}.problem h3{font-size:1.3rem;font-weight:500;margin:0 0 8px}.problem p{color:#858c94;margin:0;max-width:600px}
    .transformShell{margin-top:74px;border:1px solid var(--line);background:#07090a;position:relative;min-height:620px;overflow:hidden}.transformTop{height:48px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 16px;font:500 .62rem/1 var(--mono);letter-spacing:.14em;text-transform:uppercase;color:#747b83}.modeSwitch{display:flex}.modeSwitch button{height:30px;padding:0 12px;border:0;border-left:1px solid var(--line);background:transparent;color:#656c73;font:500 .6rem/1 var(--mono);letter-spacing:.12em;text-transform:uppercase;cursor:pointer}.modeSwitch button.active{background:#ececef;color:#0a0b0c}.transformBody{position:absolute;inset:49px 0 0}.transformGrid{position:absolute;inset:0;background-image:linear-gradient(var(--line2) 1px,transparent 1px),linear-gradient(90deg,var(--line2) 1px,transparent 1px);background-size:54px 54px;opacity:.55}.coreNode,.sysNode{position:absolute;border:1px solid var(--line);background:rgba(7,9,10,.9);font:500 .62rem/1 var(--mono);letter-spacing:.1em;text-transform:uppercase;padding:13px 14px;color:#a3a9b0;transition:1.15s cubic-bezier(.2,.75,.1,1)}.coreNode{left:50%;top:50%;transform:translate(-50%,-50%);padding:20px;color:#ded9ff;border-color:rgba(199,186,255,.48);box-shadow:0 0 50px rgba(154,130,255,.08)}.sysNode:before,.coreNode:before{content:"";width:5px;height:5px;background:#727981;display:inline-block;margin-right:8px}.coreNode:before{background:var(--signal);box-shadow:0 0 10px rgba(199,186,255,.7)}
    .n1{left:8%;top:16%}.n2{right:9%;top:12%}.n3{left:14%;bottom:15%}.n4{right:12%;bottom:18%}.n5{left:45%;top:13%}.n6{left:43%;bottom:10%}.transformShell.syntropic .n1{left:17%;top:25%}.transformShell.syntropic .n2{right:18%;top:25%}.transformShell.syntropic .n3{left:17%;bottom:25%}.transformShell.syntropic .n4{right:18%;bottom:25%}.transformShell.syntropic .n5{left:44%;top:18%}.transformShell.syntropic .n6{left:43%;bottom:18%}.transformShell.chaos .sysNode:nth-of-type(2){transform:rotate(-7deg)}.transformShell.chaos .sysNode:nth-of-type(3){transform:rotate(5deg)}.transformShell.chaos .sysNode:nth-of-type(4){transform:rotate(8deg)}.transformShell.chaos .sysNode:nth-of-type(5){transform:rotate(-5deg)}
    #transformCanvas{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.transformCaption{position:absolute;left:16px;bottom:14px;font:400 .6rem/1.4 var(--mono);letter-spacing:.1em;text-transform:uppercase;color:#5e656c}
    .operatorRail{margin-top:64px;border-top:1px solid var(--line)}.operator{display:grid;grid-template-columns:110px .8fr 1.2fr;gap:26px;padding:30px 0;border-bottom:1px solid var(--line);align-items:start}.operator .op{font:500 .62rem/1 var(--mono);letter-spacing:.14em;color:#777e86}.operator h3{font-size:1.55rem;font-weight:500;letter-spacing:-.025em;margin:0}.operator p{margin:0;color:#8e959d;max-width:650px}
    .productStage{border:1px solid var(--line);margin-top:70px;display:grid;grid-template-columns:.86fr 1.14fr;min-height:680px;background:#07090a}.productMeta{padding:42px;border-right:1px solid var(--line);display:flex;flex-direction:column;justify-content:space-between}.productMeta h3{font-size:clamp(3rem,6vw,6.5rem);line-height:.82;letter-spacing:-.065em;font-weight:500;margin:18px 0 24px}.productMeta p{color:#959ca4;max-width:480px}.statusTag{display:inline-flex;width:max-content;align-items:center;border:1px solid rgba(168,237,200,.27);color:#a9d7bd;padding:8px 10px;font:500 .59rem/1 var(--mono);letter-spacing:.12em;text-transform:uppercase}.moduleField{position:relative;min-height:680px;overflow:hidden;background:radial-gradient(circle at 50% 50%,rgba(154,130,255,.08),transparent 42%)}#ecosystemCanvas{position:absolute;inset:0;width:100%;height:100%}.moduleCore{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:150px;height:150px;border:1px solid rgba(199,186,255,.45);display:grid;place-items:center;text-align:center;font:500 .68rem/1.45 var(--mono);letter-spacing:.1em;text-transform:uppercase;color:#d9d3ff;background:#0b0c10;z-index:3}.module{position:absolute;z-index:4;border:1px solid var(--line);background:rgba(6,8,9,.93);padding:11px 12px;font:500 .59rem/1 var(--mono);letter-spacing:.08em;text-transform:uppercase;color:#969da5;cursor:default;transition:.25s}.module:hover{border-color:rgba(199,186,255,.44);color:#fff;transform:translateY(-2px)}.m1{left:11%;top:13%}.m2{left:43%;top:8%}.m3{right:10%;top:18%}.m4{right:7%;top:49%}.m5{right:12%;bottom:12%}.m6{left:43%;bottom:8%}.m7{left:10%;bottom:17%}.m8{left:8%;top:48%}
    .moduleInfo{position:absolute;left:20px;right:20px;bottom:18px;display:flex;justify-content:space-between;gap:20px;font:400 .58rem/1.5 var(--mono);letter-spacing:.08em;text-transform:uppercase;color:#626971;z-index:5}.moduleInfo b{color:#a8aeb5;font-weight:500}
    .techBand{background:#080a0c}.techGrid{display:grid;grid-template-columns:.9fr 1.1fr;gap:80px;align-items:end}.techName{font-size:clamp(3.5rem,7vw,8rem);line-height:.82;letter-spacing:-.07em;font-weight:500}.techName small{display:block;font:500 .62rem/1.4 var(--mono);letter-spacing:.18em;text-transform:uppercase;color:#6f767d;margin-bottom:26px}.techCopy{color:#999fa7;max-width:620px}.techMatrix{margin-top:52px;border-top:1px solid var(--line)}.techRow{display:grid;grid-template-columns:48px .75fr 1.25fr;gap:26px;padding:21px 0;border-bottom:1px solid var(--line);font-family:var(--mono)}.techRow .i{font-size:.6rem;color:#60676f}.techRow strong{font-size:.7rem;letter-spacing:.1em;text-transform:uppercase}.techRow span{font-size:.68rem;color:#7e858d}
    .scrollSystem{min-height:320vh;position:relative}.scrollSticky{position:sticky;top:70px;height:calc(100svh - 70px);display:grid;align-items:center;overflow:hidden;border-top:1px solid var(--line)}.scrollGrid{display:grid;grid-template-columns:.65fr 1.35fr;gap:60px;align-items:center}.stateIndex{font:500 .64rem/1 var(--mono);letter-spacing:.16em;color:#666d74;margin-bottom:28px}.stateTitle{font-size:clamp(3.4rem,6.6vw,7.5rem);line-height:.83;letter-spacing:-.068em;font-weight:500}.stateTitle span{color:var(--signal)}.stateCopy{color:#969da5;max-width:520px;margin-top:24px}.stateMeter{display:grid;grid-template-columns:repeat(5,1fr);margin-top:44px;border:1px solid var(--line)}.stateMeter div{height:4px;background:#0b0d0f;border-right:1px solid var(--line)}.stateMeter div:last-child{border-right:0}.stateMeter div.on{background:var(--signal)}.stateViz{height:min(70vh,680px);border:1px solid var(--line);position:relative;background:#07090a;overflow:hidden}.stateViz:before{content:"";position:absolute;inset:0;background-image:linear-gradient(var(--line2) 1px,transparent 1px),linear-gradient(90deg,var(--line2) 1px,transparent 1px);background-size:48px 48px}.stateOrb{position:absolute;left:50%;top:50%;width:220px;height:220px;transform:translate(-50%,-50%);border:1px solid rgba(199,186,255,.32);transition:.55s;display:grid;place-items:center}.stateOrb:before,.stateOrb:after{content:"";position:absolute;border:1px solid rgba(255,255,255,.1);inset:12%}.stateOrb:after{inset:30%;background:rgba(154,130,255,.07)}.stateOrbLabel{font:500 .62rem/1.5 var(--mono);letter-spacing:.12em;text-align:center;text-transform:uppercase;color:#bcb4e8;z-index:2}.stateSat{position:absolute;width:9px;height:9px;background:#656c73;border:1px solid #8a9198;transition:.55s}.sA{left:12%;top:20%}.sB{right:15%;top:16%}.sC{left:16%;bottom:18%}.sD{right:12%;bottom:22%}.stateViz[data-state="1"] .sA{left:25%;top:28%}.stateViz[data-state="1"] .sB{right:26%;top:26%}.stateViz[data-state="1"] .sC{left:26%;bottom:28%}.stateViz[data-state="1"] .sD{right:24%;bottom:30%}.stateViz[data-state="2"] .stateOrb{transform:translate(-50%,-50%) rotate(45deg);border-color:rgba(199,186,255,.5)}.stateViz[data-state="3"] .stateOrb{box-shadow:0 0 80px rgba(154,130,255,.14)}.stateViz[data-state="3"] .stateSat,.stateViz[data-state="4"] .stateSat{background:var(--signal);border-color:var(--signal);box-shadow:0 0 14px rgba(199,186,255,.45)}.stateViz[data-state="4"] .stateOrb{width:260px;height:260px;box-shadow:0 0 120px rgba(154,130,255,.16)}
    .arch{margin-top:68px;border:1px solid var(--line)}.archRow{display:grid;grid-template-columns:180px 1fr 180px;gap:0;border-bottom:1px solid var(--line);min-height:92px}.archRow:last-child{border-bottom:0}.archLabel{padding:22px;border-right:1px solid var(--line);font:500 .62rem/1.4 var(--mono);letter-spacing:.1em;text-transform:uppercase;color:#9299a1}.archMid{padding:22px;display:flex;align-items:center;gap:9px;flex-wrap:wrap}.archMid span{border:1px solid var(--line2);padding:7px 9px;font:400 .58rem/1 var(--mono);letter-spacing:.06em;text-transform:uppercase;color:#858c94}.archState{padding:22px;border-left:1px solid var(--line);display:grid;place-items:center;font:500 .58rem/1 var(--mono);letter-spacing:.11em;text-transform:uppercase;color:#8ebba2}
    .trust{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--line);margin-top:64px}.trust div{min-height:180px;padding:24px;border-right:1px solid var(--line)}.trust div:last-child{border-right:0}.trust .t{font:500 .61rem/1 var(--mono);letter-spacing:.13em;color:#6d747c;text-transform:uppercase}.trust strong{display:block;font-size:1.12rem;font-weight:500;margin-top:48px}.trust p{color:#777e86;font-size:.86rem;margin:8px 0 0}
    .faq{max-width:920px;margin-top:60px;border-top:1px solid var(--line)}.faqItem{border-bottom:1px solid var(--line)}.faqQ{width:100%;padding:26px 0;border:0;background:transparent;color:#e5e7e9;text-align:left;display:flex;justify-content:space-between;gap:20px;cursor:pointer;font-size:1.06rem}.faqQ i{font:400 .75rem/1 var(--mono);color:#6d747b;font-style:normal}.faqA{max-height:0;overflow:hidden;transition:max-height .35s ease;color:#8c939b;max-width:760px}.faqItem.open .faqA{max-height:220px;padding-bottom:26px}.faqItem.open .faqQ i{color:var(--signal)}
    .contactPanel{border:1px solid rgba(199,186,255,.28);background:#080a0c;padding:54px;display:grid;grid-template-columns:1fr .65fr;gap:60px;align-items:end}.contactPanel h2{font-size:clamp(3.2rem,6vw,7rem);max-width:900px}.contactMeta{border-left:1px solid var(--line);padding-left:28px;font:400 .66rem/1.8 var(--mono);letter-spacing:.08em;color:#747b83;text-transform:uppercase}.contactMeta b{display:block;color:#c2c7cc;font-weight:500;margin-bottom:16px}.pending{margin-top:18px;color:#716b91;font-size:.58rem}
    footer{border-top:1px solid var(--line);padding:34px 0 calc(34px + env(safe-area-inset-bottom));font:400 .62rem/1.5 var(--mono);letter-spacing:.09em;text-transform:uppercase;color:#697079}.footerGrid{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:20px}.footerLinks{display:flex;gap:18px}.footerRight{text-align:right}.reveal{opacity:0;transform:translateY(18px);transition:.72s cubic-bezier(.2,.75,.2,1)}.reveal.in{opacity:1;transform:none}
    @media(max-width:980px){.navin{grid-template-columns:1fr auto}.navlinks{display:none}.navright{display:block}.heroGrid,.manifestGrid,.split,.productStage,.techGrid,.scrollGrid,.contactPanel{grid-template-columns:1fr}.telemetry{display:none}.manifestGrid{gap:34px}.stickyIntro{position:relative;top:auto}.productMeta{border-right:0;border-bottom:1px solid var(--line)}.moduleField{min-height:560px}.scrollSystem{min-height:280vh}.scrollSticky{height:auto;min-height:calc(100svh - 70px);padding:70px 0}.stateViz{height:52vh}.trust{grid-template-columns:1fr 1fr}.trust div:nth-child(2){border-right:0}.trust div:nth-child(-n+2){border-bottom:1px solid var(--line)}.archRow{grid-template-columns:140px 1fr}.archState{display:none}.footerGrid{grid-template-columns:1fr auto}.footerRight{display:none}}
    @media(max-width:640px){.wrap{width:min(100% - 28px,1240px)}.nav{height:62px}.brand{font-size:.67rem}.sigil{width:27px;height:27px}.navcta{font-size:.58rem;padding:0 10px;min-height:36px}.hero{padding-top:125px;padding-bottom:48px;min-height:100svh}.heroGrid{gap:32px}.hero h1{font-size:clamp(3.65rem,18vw,6.5rem)}.heroActions{display:grid;grid-template-columns:1fr}.heroActions .btn{width:100%}.scrollCue{display:none}.section{padding:94px 0}.manifest{padding:110px 0}.systemStrip{grid-template-columns:1fr 1fr}.systemStrip div:nth-child(2){border-right:0}.systemStrip div:nth-child(-n+2){border-bottom:1px solid var(--line)}.operator{grid-template-columns:52px 1fr}.operator p{grid-column:2}.transformShell{min-height:520px}.transformTop{font-size:.54rem}.modeSwitch button{padding:0 8px}.sysNode,.coreNode{font-size:.53rem;padding:10px}.coreNode{padding:15px}.n1{left:5%;top:17%}.n2{right:4%;top:15%}.n3{left:6%;bottom:18%}.n4{right:5%;bottom:20%}.n5{left:39%;top:11%}.n6{left:37%;bottom:11%}.productMeta{padding:28px}.moduleField{min-height:480px}.moduleCore{width:118px;height:118px;font-size:.56rem}.module{font-size:.49rem;padding:9px 8px}.m1{left:5%}.m2{left:38%;top:7%}.m3{right:4%}.m4{right:3%}.m5{right:5%}.m6{left:38%}.m7{left:4%}.m8{left:3%}.moduleInfo{font-size:.49rem}.techRow{grid-template-columns:32px 1fr;gap:16px}.techRow span{grid-column:2}.stateViz{height:42vh}.stateMeter{margin-top:28px}.archRow{grid-template-columns:1fr}.archLabel{border-right:0;border-bottom:1px solid var(--line)}.trust{grid-template-columns:1fr}.trust div{border-right:0;border-bottom:1px solid var(--line)!important}.trust div:last-child{border-bottom:0!important}.contactPanel{padding:30px}.contactMeta{border-left:0;border-top:1px solid var(--line);padding:24px 0 0}.footerGrid{grid-template-columns:1fr}.footerLinks{flex-wrap:wrap}}
    @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.reveal{opacity:1;transform:none;transition:none}*{animation:none!important;transition-duration:.001ms!important}}
  </style>
</head>
<body>
<div class="progress" id="progress"></div>
<header class="nav"><div class="wrap navin"><a href="#top" class="brand"><span class="sigil"></span><span>SYNTROPIC</span></a><nav class="navlinks"><a href="#system">System</a><a href="#fullautobiz">FullAutoBIZ</a><a href="#technology">Technology</a><a href="#architecture">Architecture</a></nav><div class="navright"><a class="navcta" href="#contact">Systemgespräch <span>↗</span></a></div></div></header>
<main id="top">
  <section class="hero">
    <canvas id="heroCanvas" aria-hidden="true"></canvas><div class="heroShade"></div>
    <div class="wrap heroGrid">
      <div>
        <div class="kicker reveal"><b>SYNTROPIC</b> // BUSINESS SYSTEMS // 2026</div>
        <h1 class="reveal">Wir bauen keine <span class="mute">Webseiten.</span><br><span class="accent">Wir entwickeln Unternehmen als Systeme.</span></h1>
        <p class="heroText reveal">SYNTROPIC transformiert fragmentierte Prozesse, Daten und digitale Touchpoints in integrierte, intelligente und zunehmend autonome Business-Ökosysteme.</p>
        <div class="heroActions reveal"><a class="btn signal" href="#system">System verstehen <span>↓</span></a><a class="btn ghost" href="#contact">Transformation besprechen <span>↗</span></a></div>
      </div>
      <aside class="telemetry reveal"><div class="row"><span>Status</span><b><i class="pulse"></i>System online</b></div><div class="row"><span>Category</span><b>Business Systems</b></div><div class="row"><span>Product 01</span><b>FullAutoBIZ</b></div><div class="row"><span>Parent</span><b>RIOSYSTEMS</b></div><div class="row"><span>Principle</span><b>Syntropy</b></div></aside>
    </div><div class="scrollCue">Scroll // transform</div>
  </section>

  <section class="manifest" id="system"><div class="wrap manifestGrid"><div class="kicker reveal">CATEGORY_01 // SYNTROPY</div><div><div class="manifestQuote reveal">Unternehmen sind heute Sammlungen von Tools. <span class="violet">Wir machen daraus ein operatives System.</span></div><p class="manifestCopy reveal">Nicht Software neben Software. Nicht Abteilungen als Inseln. Nicht Menschen als manuelle Schnittstellen. Wir syntropisieren die Architektur des Unternehmens, bis Daten, Systeme, Prozesse und Intelligenz als ein zusammenhängendes Ökosystem arbeiten.</p></div></div><div class="wrap systemStrip reveal"><div><span>01 // Order</span><strong>Ordnung statt Chaos.</strong></div><div><span>02 // Integration</span><strong>Integration statt Insellösungen.</strong></div><div><span>03 // Intelligence</span><strong>Intelligenz statt Übergaben.</strong></div><div><span>04 // Evolution</span><strong>Evolution statt Verwaltung.</strong></div></div></section>

  <section class="section"><div class="wrap split"><div class="stickyIntro"><div class="kicker reveal">CURRENT STATE // FRICTION</div><h2 class="reveal">Wachstum darf nicht bedeuten, mehr Chaos zu verwalten.</h2><p class="lead reveal">Die meisten Unternehmen skalieren zuerst ihre Komplexität. Mehr Tools, mehr Übergaben, mehr Koordination. SYNTROPIC setzt am Systemzustand an.</p></div><div class="problemList"><article class="problem reveal"><div class="num">01</div><div><h3>Fragmentierte Softwarelandschaft</h3><p>CRM, Marketing, Support, Daten und Kommunikation erzeugen lokale Optimierung, aber kein gemeinsames Betriebsmodell.</p></div></article><article class="problem reveal"><div class="num">02</div><div><h3>Menschen als API</h3><p>Information wird kopiert, weitergeleitet, erklärt und erinnert. Operative Kapazität verschwindet in Übergaben.</p></div></article><article class="problem reveal"><div class="num">03</div><div><h3>Unsichtbare Zustände</h3><p>Entscheidungen basieren auf Ausschnitten. Daten existieren, aber nicht als konsistentes Systembild.</p></div></article><article class="problem reveal"><div class="num">04</div><div><h3>Automatisierung ohne Architektur</h3><p>Einzelne Automationen beschleunigen Teilprozesse, können aber neue Abhängigkeiten und neue Wartung erzeugen.</p></div></article><article class="problem reveal"><div class="num">05</div><div><h3>KI ohne operative Einbettung</h3><p>Modelle bleiben Assistenten, wenn ihnen Datenzugang, Zuständigkeit, Workflows und klare Systemgrenzen fehlen.</p></div></article></div></div></section>

  <section class="section"><div class="wrap"><div class="kicker reveal">STATE TRANSITION // INTERACTIVE</div><h2 class="reveal">Von Fragmentierung zu Syntropie.</h2><p class="lead reveal">Schalte den Systemzustand um. Nicht mehr Funktionen stehen im Zentrum, sondern ihre Beziehungen.</p><div class="transformShell chaos reveal" id="transformShell"><div class="transformTop"><span>BUSINESS ECOSYSTEM // STATE MAP</span><div class="modeSwitch"><button class="active" data-mode="chaos">Fragmented</button><button data-mode="syntropic">Syntropic</button></div></div><div class="transformBody"><div class="transformGrid"></div><canvas id="transformCanvas"></canvas><div class="sysNode n1">Website</div><div class="sysNode n2">Marketing</div><div class="sysNode n3">Support</div><div class="sysNode n4">CRM</div><div class="sysNode n5">Data</div><div class="sysNode n6">Operations</div><div class="coreNode">SYNTROPIC<br>CORE</div><div class="transformCaption" id="transformCaption">State: fragmented // isolated signals // manual bridges</div></div></div>
      <div class="operatorRail"><article class="operator reveal"><div class="op">01 // MAP</div><h3>Zustand sichtbar machen.</h3><p>Prozesse, Daten, Rollen, Systeme, Unknowns und Abhängigkeiten werden als operatives Gesamtbild rekonstruiert.</p></article><article class="operator reveal"><div class="op">02 // SYNTHESIZE</div><h3>Architektur reduzieren und verbinden.</h3><p>Redundanzen werden entfernt, Schnittstellen vereinheitlicht und Systeme entlang einer gemeinsamen Daten- und Workflowlogik gekoppelt.</p></article><article class="operator reveal"><div class="op">03 // INTELLIGIZE</div><h3>Intelligenz in den Betrieb integrieren.</h3><p>KI erhält Kontext, Zuständigkeit und Handlungspfade. Nicht als isoliertes Tool, sondern als Bestandteil des Systems.</p></article><article class="operator reveal"><div class="op">04 // EVOLVE</div><h3>Das System lernfähig machen.</h3><p>Feedback, Messung und wiederholbare Anpassung schaffen ein Unternehmen, das nicht nur läuft, sondern sich verbessert.</p></article></div>
    </div></section>

  <section class="section" id="fullautobiz"><div class="wrap"><div class="kicker reveal">PRODUCT FAMILY // 01 // DEPLOYABLE</div><h2 class="reveal">FullAutoBIZ ist keine Leistungsliste.<br>Es ist eine Business-System-Architektur.</h2><p class="lead reveal">Die Module können einzeln eingesetzt werden. Ihr größter Wert entsteht jedoch, wenn sie Daten, Entscheidungen und Aktionen als ein gemeinsames Betriebssystem teilen.</p><div class="productStage reveal"><div class="productMeta"><div><span class="statusTag"><i class="pulse"></i>Product family active</span><h3>Full<br>Auto<br>BIZ</h3><p>Nahezu vollständig automatisierte Unternehmen, in denen Marktauftritt, Leadgenerierung, CRM, Support, interne KI, Produktlogik, Daten und Workflows als ein System arbeiten.</p></div><div class="kicker">MODULES // INDEPENDENT + COMPOSABLE</div></div><div class="moduleField"><canvas id="ecosystemCanvas"></canvas><div class="moduleCore">BUSINESS<br>SYSTEM<br>CORE</div><div class="module m1">Premium Website</div><div class="module m2">Lead Engine</div><div class="module m3">Marketing</div><div class="module m4">CRM</div><div class="module m5">Customer AI</div><div class="module m6">Internal AI</div><div class="module m7">Product Engine</div><div class="module m8">Data + Workflows</div><div class="moduleInfo"><span><b>Signal flow</b> // event-driven</span><span><b>Mode</b> // modular system</span></div></div></div></div></section>

  <section class="section techBand" id="technology"><div class="wrap techGrid"><div class="techName reveal"><small>Parent company // research + base technology</small>RIO<br>SYSTEMS</div><div><p class="techCopy reveal">RIOSYSTEMS entwickelt Forschung, KI-Systeme und Basistechnologien. SYNTROPIC ist die operative Marke, die diese Fähigkeiten in marktfähige Business-Systeme übersetzt. Forschung wird Infrastruktur. Infrastruktur wird operative Wertschöpfung.</p><div class="techMatrix reveal"><div class="techRow"><div class="i">01</div><strong>AI Systems</strong><span>Reasoning, agents, knowledge and controlled action paths.</span></div><div class="techRow"><div class="i">02</div><strong>Data Architecture</strong><span>Events, state, CRM, observability and business context.</span></div><div class="techRow"><div class="i">03</div><strong>Automation Layer</strong><span>Triggers, workflows, integrations and deterministic execution.</span></div><div class="techRow"><div class="i">04</div><strong>Business Intelligence</strong><span>Operational visibility, feedback loops and decision support.</span></div></div></div></div></section>

  <section class="scrollSystem" id="transformation"><div class="scrollSticky"><div class="wrap scrollGrid"><div><div class="stateIndex" id="stateIndex">STATE_01 / 05</div><div class="stateTitle" id="stateTitle">Observe<span>.</span></div><p class="stateCopy" id="stateCopy">Der reale Unternehmenszustand wird sichtbar. Nicht die Wunscharchitektur, sondern das, was tatsächlich existiert.</p><div class="stateMeter" id="stateMeter"><div class="on"></div><div></div><div></div><div></div><div></div></div></div><div class="stateViz" id="stateViz" data-state="0"><div class="stateOrb"><div class="stateOrbLabel" id="stateOrbLabel">BUSINESS<br>STATE</div></div><i class="stateSat sA"></i><i class="stateSat sB"></i><i class="stateSat sC"></i><i class="stateSat sD"></i></div></div></div></section>

  <section class="section" id="architecture"><div class="wrap"><div class="kicker reveal">REFERENCE ARCHITECTURE // V1</div><h2 class="reveal">Ein syntropisches Unternehmen besitzt klare Ebenen.</h2><p class="lead reveal">Nicht jede Technologie darf alles. Jede Ebene kennt Zweck, Daten und Handlungsraum. Dadurch entsteht Skalierbarkeit ohne Kontrollverlust.</p><div class="arch reveal"><div class="archRow"><div class="archLabel">Experience Layer</div><div class="archMid"><span>Web</span><span>Sales</span><span>Customer UI</span><span>Support</span></div><div class="archState">Connected</div></div><div class="archRow"><div class="archLabel">Automation Layer</div><div class="archMid"><span>Events</span><span>Triggers</span><span>Workflows</span><span>Integrations</span></div><div class="archState">Orchestrated</div></div><div class="archRow"><div class="archLabel">Intelligence Layer</div><div class="archMid"><span>Agents</span><span>Knowledge</span><span>Decisions</span><span>Guardrails</span></div><div class="archState">Contextual</div></div><div class="archRow"><div class="archLabel">Data Layer</div><div class="archMid"><span>CRM</span><span>State</span><span>Events</span><span>Business Data</span></div><div class="archState">Observable</div></div><div class="archRow"><div class="archLabel">Infrastructure Layer</div><div class="archMid"><span>Cloud</span><span>Security</span><span>Identity</span><span>Monitoring</span></div><div class="archState">Controlled</div></div></div>
      <div class="trust reveal"><div><span class="t">Principle 01</span><strong>Architecture first.</strong><p>Technologie folgt dem Systemzustand, nicht umgekehrt.</p></div><div><span class="t">Principle 02</span><strong>Modular deployment.</strong><p>Einzelne Module können starten und später integriert wachsen.</p></div><div><span class="t">Principle 03</span><strong>Human override.</strong><p>Autonomie braucht klare Grenzen, Rollen und Eingriffspunkte.</p></div><div><span class="t">Principle 04</span><strong>Observable state.</strong><p>Systeme werden messbar, damit Evolution kontrollierbar bleibt.</p></div></div>
    </div></section>

  <section class="section"><div class="wrap"><div class="kicker reveal">FAQ // SYSTEM QUESTIONS</div><h2 class="reveal">Keine Agentur.<br>Keine Tool-Sammlung.</h2><div class="faq"><div class="faqItem reveal"><button class="faqQ"><span>Ist SYNTROPIC eine Agentur?</span><i>[+]</i></button><div class="faqA">Nein. SYNTROPIC entwickelt Business-Ökosysteme. Webseiten, CRM, Automationen und KI sind mögliche Systemmodule, aber nicht die Kategorie unseres Angebots.</div></div><div class="faqItem reveal"><button class="faqQ"><span>Muss ein Unternehmen komplett neu aufgebaut werden?</span><i>[+]</i></button><div class="faqA">Nein. Bestehende Strukturen können gemappt, reduziert, verbunden und schrittweise syntropisiert werden. Der Einstieg kann bewusst modular erfolgen.</div></div><div class="faqItem reveal"><button class="faqQ"><span>Was unterscheidet FullAutoBIZ von einem Automatisierungsprojekt?</span><i>[+]</i></button><div class="faqA">Ein Automatisierungsprojekt optimiert meist einzelne Abläufe. FullAutoBIZ betrachtet Marktauftritt, Daten, CRM, KI, Workflows und operative Logik als zusammenhängende Architektur.</div></div><div class="faqItem reveal"><button class="faqQ"><span>Für welche Unternehmen ist das relevant?</span><i>[+]</i></button><div class="faqA">Für Unternehmer, Startups, Mittelstand, Wachstumsunternehmen, Investoren und digitale Unternehmen, deren operative Komplexität schneller wächst als ihre Systemarchitektur.</div></div></div></div></section>

  <section class="section" id="contact"><div class="wrap"><div class="contactPanel reveal"><div><div class="kicker"><b>ENTRY POINT</b> // SYSTEM CONVERSATION</div><h2>Dein Unternehmen muss nicht mehr Tools bekommen. Es muss als System funktionieren.</h2><div class="heroActions"><a class="btn signal" href="#top">Systembrief vorbereiten <span>↗</span></a></div></div><aside class="contactMeta"><b>Gesprächsrahmen</b>01 // aktueller Systemzustand<br>02 // operative Reibung<br>03 // mögliche Syntropisierung<br>04 // sinnvoller Einstieg<div class="pending">Kontaktkanal wird vor Production-Launch final verbunden.</div></aside></div></div></section>
</main>
<footer><div class="wrap footerGrid"><a href="#top" class="brand"><span class="sigil"></span><span>SYNTROPIC</span></a><div class="footerLinks"><a href="#system">System</a><a href="#fullautobiz">FullAutoBIZ</a><a href="#technology">Technology</a><a href="#contact">Contact</a></div><div class="footerRight">© 2026 // A RIOSYSTEMS COMPANY</div></div></footer>
<script>
(function(){
  var reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var q=function(s,r){return (r||document).querySelector(s)};var qa=function(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))};
  function reveal(){qa('.reveal').forEach(function(el){if(el.getBoundingClientRect().top<window.innerHeight*.9)el.classList.add('in')})}
  function progress(){var d=document.documentElement;var max=d.scrollHeight-d.clientHeight;q('#progress').style.width=(max?d.scrollTop/max*100:0)+'%'}
  reveal();progress();window.addEventListener('scroll',function(){reveal();progress();updateScrollState()},{passive:true});
  qa('.faqQ').forEach(function(btn){btn.addEventListener('click',function(){var item=btn.parentElement;item.classList.toggle('open');q('i',btn).textContent=item.classList.contains('open')?'[-]':'[+]'})});

  var shell=q('#transformShell'),caption=q('#transformCaption');
  qa('.modeSwitch button').forEach(function(btn){btn.addEventListener('click',function(){qa('.modeSwitch button').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');var syn=btn.getAttribute('data-mode')==='syntropic';shell.classList.toggle('syntropic',syn);shell.classList.toggle('chaos',!syn);caption.textContent=syn?'State: syntropic // shared context // connected execution':'State: fragmented // isolated signals // manual bridges';drawTransform(syn)})});

  function fitCanvas(c){var r=c.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);c.width=Math.max(1,r.width*dpr);c.height=Math.max(1,r.height*dpr);var x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);return {ctx:x,w:r.width,h:r.height}}
  function heroNetwork(){var c=q('#heroCanvas');if(!c)return;var f=fitCanvas(c),ctx=f.ctx,w=f.w,h=f.h;var pts=[];var count=Math.max(34,Math.floor(w/26));for(var i=0;i<count;i++)pts.push({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.16,vy:(Math.random()-.5)*.16,r:Math.random()*1.6+.45});function frame(){ctx.clearRect(0,0,w,h);for(var i=0;i<pts.length;i++){var a=pts[i];a.x+=a.vx;a.y+=a.vy;if(a.x<0||a.x>w)a.vx*=-1;if(a.y<0||a.y>h)a.vy*=-1;for(var j=i+1;j<pts.length;j++){var b=pts[j],dx=a.x-b.x,dy=a.y-b.y,dist=Math.sqrt(dx*dx+dy*dy);if(dist<150){ctx.strokeStyle='rgba(199,186,255,'+(0.13*(1-dist/150))+')';ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}ctx.fillStyle='rgba(220,216,235,.42)';ctx.beginPath();ctx.arc(a.x,a.y,a.r,0,Math.PI*2);ctx.fill()}if(!reduced)requestAnimationFrame(frame)}frame()}

  function nodeCenter(el,base){var r=el.getBoundingClientRect(),b=base.getBoundingClientRect();return {x:r.left-b.left+r.width/2,y:r.top-b.top+r.height/2}}
  function drawTransform(syn){var c=q('#transformCanvas'),base=q('.transformBody');if(!c||!base)return;var f=fitCanvas(c),ctx=f.ctx;ctx.clearRect(0,0,f.w,f.h);var core=nodeCenter(q('.coreNode'),base);qa('.sysNode',base).forEach(function(n){var p=nodeCenter(n,base);ctx.setLineDash(syn?[]:[5,10]);ctx.strokeStyle=syn?'rgba(199,186,255,.42)':'rgba(130,136,143,.18)';ctx.lineWidth=syn?1:.7;ctx.beginPath();ctx.moveTo(p.x,p.y);if(syn){var mx=(p.x+core.x)/2;ctx.bezierCurveTo(mx,p.y,mx,core.y,core.x,core.y)}else{ctx.lineTo(core.x+(Math.random()-.5)*80,core.y+(Math.random()-.5)*80)}ctx.stroke()});ctx.setLineDash([])}

  function ecosystem(){var c=q('#ecosystemCanvas'),field=q('.moduleField');if(!c||!field)return;var f=fitCanvas(c),ctx=f.ctx;var core=nodeCenter(q('.moduleCore'),field);ctx.clearRect(0,0,f.w,f.h);qa('.module',field).forEach(function(n,idx){var p=nodeCenter(n,field);ctx.strokeStyle='rgba(199,186,255,.28)';ctx.lineWidth=.8;ctx.beginPath();ctx.moveTo(core.x,core.y);var mx=(core.x+p.x)/2;ctx.bezierCurveTo(mx,core.y,mx,p.y,p.x,p.y);ctx.stroke();var t=(Date.now()/2200+idx*.13)%1;var x=(1-t)*(1-t)*(1-t)*core.x+3*(1-t)*(1-t)*t*mx+3*(1-t)*t*t*mx+t*t*t*p.x;var y=(1-t)*(1-t)*(1-t)*core.y+3*(1-t)*(1-t)*t*core.y+3*(1-t)*t*t*p.y+t*t*t*p.y;ctx.fillStyle='rgba(199,186,255,.85)';ctx.beginPath();ctx.arc(x,y,2,0,Math.PI*2);ctx.fill()});if(!reduced)requestAnimationFrame(ecosystem)}

  var states=[
    ['Observe','Der reale Unternehmenszustand wird sichtbar. Nicht die Wunscharchitektur, sondern das, was tatsächlich existiert.','BUSINESS\\nSTATE'],
    ['Reduce','Redundanzen, unnötige Übergaben und konkurrierende Datenpfade werden identifiziert und reduziert.','REDUCED\\nFRICTION'],
    ['Integrate','Daten, Systeme und Workflows erhalten eine gemeinsame Architektur und klare Schnittstellen.','SHARED\\nCONTEXT'],
    ['Intelligize','KI wird mit Kontext, Zuständigkeit und kontrollierten Handlungspfaden in den Betrieb eingebettet.','OPERATIVE\\nAI'],
    ['Evolve','Messung und Feedback machen das Unternehmen adaptiv. Aus Betrieb wird ein lernendes System.','EVOLVING\\nSYSTEM']
  ];
  function updateScrollState(){var sec=q('.scrollSystem');if(!sec)return;var r=sec.getBoundingClientRect();var total=sec.offsetHeight-window.innerHeight;var pos=Math.min(Math.max(-r.top,0),Math.max(total,1));var idx=Math.min(4,Math.floor((pos/Math.max(total,1))*5));q('#stateIndex').textContent='STATE_0'+(idx+1)+' / 05';q('#stateTitle').innerHTML=states[idx][0]+'<span>.</span>';q('#stateCopy').textContent=states[idx][1];q('#stateOrbLabel').innerHTML=states[idx][2].replace('\\n','<br>');q('#stateViz').setAttribute('data-state',String(idx));qa('#stateMeter div').forEach(function(el,i){el.classList.toggle('on',i<=idx)})}

  function resize(){heroNetwork();setTimeout(function(){drawTransform(shell.classList.contains('syntropic'));ecosystem()},40)}
  window.addEventListener('resize',function(){clearTimeout(window.__synResize);window.__synResize=setTimeout(resize,180)});
  heroNetwork();drawTransform(false);ecosystem();updateScrollState();
  if(!reduced){var auto=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){setTimeout(function(){var b=q('.modeSwitch button[data-mode="syntropic"]');if(b)b.click()},650);auto.disconnect()}})},{threshold:.5});auto.observe(shell)}
})();
</script>
</body>
</html>`;
